///************************************************
/// Generated by: LinhDH
/// Date: 22/05/2015 08:43:53
/// Goal: Create User Service Class for DM_LOAI_YEU_CAU
///************************************************
/// <summary>
/// Create User Service Class for DM_LOAI_YEU_CAU
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DM_LOAI_YEU_CAU : US_Object
	{
		private const string c_TableName = "DM_LOAI_YEU_CAU";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public decimal dcID_CHA 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_CHA", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_CHA"] = value;
			}
		}

		public bool IsID_CHANull()	{
			return pm_objDR.IsNull("ID_CHA");
		}

		public void SetID_CHANull() {
			pm_objDR["ID_CHA"] = System.Convert.DBNull;
		}

		public string strTEN_YEU_CAU 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_YEU_CAU", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_YEU_CAU"] = value;
			}
		}

		public bool IsTEN_YEU_CAUNull() 
		{
			return pm_objDR.IsNull("TEN_YEU_CAU");
		}

		public void SetTEN_YEU_CAUNull() {
			pm_objDR["TEN_YEU_CAU"] = System.Convert.DBNull;
		}

		public string strSU_DUNG_YN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "SU_DUNG_YN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["SU_DUNG_YN"] = value;
			}
		}

		public bool IsSU_DUNG_YNNull() 
		{
			return pm_objDR.IsNull("SU_DUNG_YN");
		}

		public void SetSU_DUNG_YNNull() {
			pm_objDR["SU_DUNG_YN"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DM_LOAI_YEU_CAU() 
		{
			pm_objDS = new DS_DM_LOAI_YEU_CAU();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_LOAI_YEU_CAU(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_LOAI_YEU_CAU(decimal i_dbID) 
		{
			pm_objDS = new DS_DM_LOAI_YEU_CAU();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

        #region Additional Functions
        public void load_ds_loai_dich_vu(DS_DM_LOAI_YEU_CAU op_ds)
        {
            CStoredProc v_cstore = new CStoredProc("pr_DM_LOAI_YEU_CAU_load_ds_loai_dich_vu");
            v_cstore.fillDataSetByCommand(this, op_ds);
        }
        public void load_ds_dich_vu_by_loai(decimal ip_dc_id_loai_dv, DS_DM_LOAI_YEU_CAU op_ds)
        {
            CStoredProc v_cstore = new CStoredProc("pr_DM_LOAI_YEU_CAU_load_ds_dich_vu_by_loai");
            v_cstore.addDecimalInputParam("@ID_LOAI_DICH_VU", ip_dc_id_loai_dv);
            v_cstore.fillDataSetByCommand(this, op_ds);
        }
        #endregion
    }
}
