///************************************************
/// Generated by: thelk
/// Date: 12/03/2014 06:39:00
/// Goal: Create User Service Class for GD_CUOC_GOI_YEU_CAU
///************************************************
/// <summary>
/// Create User Service Class for GD_CUOC_GOI_YEU_CAU
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using IPCOREDS.CDBNames;


namespace IPCOREUS
{

	public class US_GD_CUOC_GOI_YEU_CAU : US_Object
	{
		private const string c_TableName = "GD_CUOC_GOI_YEU_CAU";
		#region Public Properties
        public decimal dcTHOI_DIEM_GOI
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "THOI_DIEM_GOI", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["THOI_DIEM_GOI"] = value;
            }
        }

        public bool IsTHOI_DIEM_GOINull()
        {
            return pm_objDR.IsNull("THOI_DIEM_GOI");
        }

        public void SetTHOI_DIEM_GOINull()
        {
            pm_objDR["THOI_DIEM_GOI"] = System.Convert.DBNull;
        }
        //
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strHO_TEN_SINH_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "HO_TEN_SINH_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["HO_TEN_SINH_VIEN"] = value;
			}
		}

		public bool IsHO_TEN_SINH_VIENNull() 
		{
			return pm_objDR.IsNull("HO_TEN_SINH_VIEN");
		}

		public void SetHO_TEN_SINH_VIENNull() {
			pm_objDR["HO_TEN_SINH_VIEN"] = System.Convert.DBNull;
		}

		public string strSO_DIEN_THOAI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "SO_DIEN_THOAI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["SO_DIEN_THOAI"] = value;
			}
		}

		public bool IsSO_DIEN_THOAINull() 
		{
			return pm_objDR.IsNull("SO_DIEN_THOAI");
		}

		public void SetSO_DIEN_THOAINull() {
			pm_objDR["SO_DIEN_THOAI"] = System.Convert.DBNull;
		}

		public string strMA_SINH_VIEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_SINH_VIEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_SINH_VIEN"] = value;
			}
		}

		public bool IsMA_SINH_VIENNull() 
		{
			return pm_objDR.IsNull("MA_SINH_VIEN");
		}

		public void SetMA_SINH_VIENNull() {
			pm_objDR["MA_SINH_VIEN"] = System.Convert.DBNull;
		}

		public DateTime datNGAY_SINH
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "NGAY_SINH", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["NGAY_SINH"] = value;
			}
		}

		public bool IsNGAY_SINHNull()
		{
			return pm_objDR.IsNull("NGAY_SINH");
		}

		public void SetNGAY_SINHNull()
		{
			pm_objDR["NGAY_SINH"] = System.Convert.DBNull;
		}

		public string strNOI_SINH 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "NOI_SINH", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["NOI_SINH"] = value;
			}
		}

		public bool IsNOI_SINHNull() 
		{
			return pm_objDR.IsNull("NOI_SINH");
		}

		public void SetNOI_SINHNull() {
			pm_objDR["NOI_SINH"] = System.Convert.DBNull;
		}

		public string strLOP 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "LOP", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["LOP"] = value;
			}
		}

		public bool IsLOPNull() 
		{
			return pm_objDR.IsNull("LOP");
		}

		public void SetLOPNull() {
			pm_objDR["LOP"] = System.Convert.DBNull;
		}

		public string strTRUONG 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TRUONG", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TRUONG"] = value;
			}
		}

		public bool IsTRUONGNull() 
		{
			return pm_objDR.IsNull("TRUONG");
		}

		public void SetTRUONGNull() {
			pm_objDR["TRUONG"] = System.Convert.DBNull;
		}

		public decimal dcID_NGUOI_DUNG 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_DUNG", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_NGUOI_DUNG"] = value;
			}
		}

		public bool IsID_NGUOI_DUNGNull()	{
			return pm_objDR.IsNull("ID_NGUOI_DUNG");
		}

		public void SetID_NGUOI_DUNGNull() {
			pm_objDR["ID_NGUOI_DUNG"] = System.Convert.DBNull;
		}

		public decimal dcID_CUOC_GOI_LIEN_QUAN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_CUOC_GOI_LIEN_QUAN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_CUOC_GOI_LIEN_QUAN"] = value;
			}
		}

		public bool IsID_CUOC_GOI_LIEN_QUANNull()	{
			return pm_objDR.IsNull("ID_CUOC_GOI_LIEN_QUAN");
		}

		public void SetID_CUOC_GOI_LIEN_QUANNull() {
			pm_objDR["ID_CUOC_GOI_LIEN_QUAN"] = System.Convert.DBNull;
		}

		public decimal dcID_CAU_HOI_LIEN_QUAN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_CAU_HOI_LIEN_QUAN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_CAU_HOI_LIEN_QUAN"] = value;
			}
		}

		public bool IsID_CAU_HOI_LIEN_QUANNull()	{
			return pm_objDR.IsNull("ID_CAU_HOI_LIEN_QUAN");
		}

		public void SetID_CAU_HOI_LIEN_QUANNull() {
			pm_objDR["ID_CAU_HOI_LIEN_QUAN"] = System.Convert.DBNull;
		}

		public string strNOI_DUNG_TRAO_DOI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "NOI_DUNG_TRAO_DOI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["NOI_DUNG_TRAO_DOI"] = value;
			}
		}

		public bool IsNOI_DUNG_TRAO_DOINull() 
		{
			return pm_objDR.IsNull("NOI_DUNG_TRAO_DOI");
		}

		public void SetNOI_DUNG_TRAO_DOINull() {
			pm_objDR["NOI_DUNG_TRAO_DOI"] = System.Convert.DBNull;
		}

		public decimal dcID_TRANG_THAI 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_TRANG_THAI"] = value;
			}
		}

		public bool IsID_TRANG_THAINull()	{
			return pm_objDR.IsNull("ID_TRANG_THAI");
		}

		public void SetID_TRANG_THAINull() {
			pm_objDR["ID_TRANG_THAI"] = System.Convert.DBNull;
		}

		public string strCUOC_GOI_VAO_YN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "CUOC_GOI_VAO_YN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["CUOC_GOI_VAO_YN"] = value;
			}
		}

		public bool IsCUOC_GOI_VAO_YNNull() 
		{
			return pm_objDR.IsNull("CUOC_GOI_VAO_YN");
		}

		public void SetCUOC_GOI_VAO_YNNull() {
			pm_objDR["CUOC_GOI_VAO_YN"] = System.Convert.DBNull;
		}

        public string strCALL_ID
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "CALL_ID", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["CALL_ID"] = value;
            }
        }

        public bool IsCALL_IDNull()
        {
            return pm_objDR.IsNull("CALL_ID");
        }

        public void SetCALL_IDNull()
        {
            pm_objDR["CALL_ID"] = System.Convert.DBNull;
        }

		public string strVOICE_CALL_LINK 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "VOICE_CALL_LINK", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["VOICE_CALL_LINK"] = value;
			}
		}

		public bool IsVOICE_CALL_LINKNull() 
		{
			return pm_objDR.IsNull("VOICE_CALL_LINK");
		}

		public void SetVOICE_CALL_LINKNull() {
			pm_objDR["VOICE_CALL_LINK"] = System.Convert.DBNull;
		}

		public DateTime datSTART_TIME
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "START_TIME", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["START_TIME"] = value;
			}
		}

		public bool IsSTART_TIMENull()
		{
			return pm_objDR.IsNull("START_TIME");
		}

		public void SetSTART_TIMENull()
		{
			pm_objDR["START_TIME"] = System.Convert.DBNull;
		}

		public DateTime datEND_TIME
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "END_TIME", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["END_TIME"] = value;
			}
		}

		public bool IsEND_TIMENull()
		{
			return pm_objDR.IsNull("END_TIME");
		}

		public void SetEND_TIMENull()
		{
			pm_objDR["END_TIME"] = System.Convert.DBNull;
		}

		public decimal dcSTATION_ID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "STATION_ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["STATION_ID"] = value;
			}
		}

		public bool IsSTATION_IDNull()	{
			return pm_objDR.IsNull("STATION_ID");
		}

		public void SetSTATION_IDNull() {
			pm_objDR["STATION_ID"] = System.Convert.DBNull;
		}

		public decimal dcDURATION 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "DURATION", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["DURATION"] = value;
			}
		}

		public bool IsDURATIONNull()	{
			return pm_objDR.IsNull("DURATION");
		}

		public void SetDURATIONNull() {
			pm_objDR["DURATION"] = System.Convert.DBNull;
		}

		public string strSTATUS 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "STATUS", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["STATUS"] = value;
			}
		}

		public bool IsSTATUSNull() 
		{
			return pm_objDR.IsNull("STATUS");
		}

		public void SetSTATUSNull() {
			pm_objDR["STATUS"] = System.Convert.DBNull;
		}

		public string strERROR_CODE 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "ERROR_CODE", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["ERROR_CODE"] = value;
			}
		}

		public bool IsERROR_CODENull() 
		{
			return pm_objDR.IsNull("ERROR_CODE");
		}

		public void SetERROR_CODENull() {
			pm_objDR["ERROR_CODE"] = System.Convert.DBNull;
		}

		public string strERROR_DESC 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "ERROR_DESC", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["ERROR_DESC"] = value;
			}
		}

		public bool IsERROR_DESCNull() 
		{
			return pm_objDR.IsNull("ERROR_DESC");
		}

		public void SetERROR_DESCNull() {
			pm_objDR["ERROR_DESC"] = System.Convert.DBNull;
		}

		public DateTime datDATETIME_RESPOND
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "DATETIME_RESPOND", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["DATETIME_RESPOND"] = value;
			}
		}

		public bool IsDATETIME_RESPONDNull()
		{
			return pm_objDR.IsNull("DATETIME_RESPOND");
		}

		public void SetDATETIME_RESPONDNull()
		{
			pm_objDR["DATETIME_RESPOND"] = System.Convert.DBNull;
		}

		public decimal dcRINGTIME 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "RINGTIME", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["RINGTIME"] = value;
			}
		}

		public bool IsRINGTIMENull()	{
			return pm_objDR.IsNull("RINGTIME");
		}

		public void SetRINGTIMENull() {
			pm_objDR["RINGTIME"] = System.Convert.DBNull;
		}

        public string strHO_TEN_QLHT
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "HO_TEN_QLHT", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["HO_TEN_QLHT"] = value;
            }
        }

        public bool IsHO_TEN_QLHTNull()
        {
            return pm_objDR.IsNull("HO_TEN_QLHT");
        }

        public void SetHO_TEN_QLHTNull()
        {
            pm_objDR["HO_TEN_QLHT"] = System.Convert.DBNull;
        }

        public string strDIEN_THOAI_QLHT
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DIEN_THOAI_QLHT", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DIEN_THOAI_QLHT"] = value;
            }
        }

        public bool IsDIEN_THOAI_QLHTNull()
        {
            return pm_objDR.IsNull("DIEN_THOAI_QLHT");
        }

        public void SetDIEN_THOAI_QLHTNull()
        {
            pm_objDR["DIEN_THOAI_QLHT"] = System.Convert.DBNull;
        }

		#endregion


		#region Init Functions
		public US_GD_CUOC_GOI_YEU_CAU() 
		{
			pm_objDS = new DS_GD_CUOC_GOI_YEU_CAU();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_GD_CUOC_GOI_YEU_CAU(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_GD_CUOC_GOI_YEU_CAU(decimal i_dbID) 
		{
			pm_objDS = new DS_GD_CUOC_GOI_YEU_CAU();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

        #region Additional Function
        public void fill_danh_sach_yeu_cau_hoc_vien(DS_GD_CUOC_GOI_YEU_CAU i_ds
                                          , string dien_thoai
                                           , string i_str_ho_ten
                                           , DateTime i_dt_tu_ngay
                                           , DateTime i_dt_den_ngay
                                           , decimal i_dc_id_trang_thai)
        {
            CStoredProc v_cstore = new CStoredProc("pr_GD_CUOC_GOI_YEU_CAU_fill_danh_sach_yeu_cau_hoc_vien");
            v_cstore.addNVarcharInputParam("@DIEN_THOAI", dien_thoai);
            v_cstore.addNVarcharInputParam("@HO_TEN", i_str_ho_ten);
            v_cstore.addDatetimeInputParam("@TU_NGAY", i_dt_tu_ngay);
            v_cstore.addDatetimeInputParam("@DEN_NGAY", i_dt_den_ngay);
            v_cstore.addDecimalInputParam("@ID_TRANG_THAI", i_dc_id_trang_thai);
            v_cstore.fillDataSetByCommand(this, i_ds);
        }
        public void load_ds_yeu_cau_hoc_vien_portal(DS_GD_CUOC_GOI_YEU_CAU i_ds
                                          , string dien_thoai
                                           , string i_str_ho_ten
                                           , DateTime i_dt_tu_ngay
                                           , DateTime i_dt_den_ngay
                                            ,decimal i_dc_thoi_diem_goi
                                           , decimal i_dc_id_nguoi_dung)
        {
            CStoredProc v_cstore = new CStoredProc("pr_GD_CUOC_GOI_YEU_CAU_load_ds_yeu_cau_hoc_vien_portal");
            v_cstore.addNVarcharInputParam("@DIEN_THOAI", dien_thoai);
            v_cstore.addNVarcharInputParam("@HO_TEN", i_str_ho_ten);
            v_cstore.addDatetimeInputParam("@TU_NGAY", i_dt_tu_ngay);
            v_cstore.addDatetimeInputParam("@DEN_NGAY", i_dt_den_ngay);
            v_cstore.addDecimalInputParam("@ID_NGUOI_DUNG", i_dc_id_nguoi_dung);
            v_cstore.addDecimalInputParam("@THOI_DIEM_GOI", i_dc_thoi_diem_goi);
            v_cstore.fillDataSetByCommand(this, i_ds);
        }
        public DataSet load_bao_cao_cham_cong(DateTime i_dt_tu_ngay
                                          , DateTime i_dt_den_ngay
                                          , decimal i_dc_id_nguoi_dung)
        {
            DataSet v_ds = new DataSet();
            CStoredProc v_cstore = new CStoredProc("pr_load_ds_cham_cong");
            v_cstore.addDatetimeInputParam("@TU_NGAY", i_dt_tu_ngay);
            v_cstore.addDatetimeInputParam("@DEN_NGAY", i_dt_den_ngay);
            v_cstore.addDecimalInputParam("@ID_NGUOI_DUNG", i_dc_id_nguoi_dung);
            v_cstore.fillData2DataSet(this, v_ds);
            return v_ds;
        }
        public bool is_call_id_exist(string ip_str_call_id)
        {
            DS_GD_CUOC_GOI_YEU_CAU v_ds_gd_cuoc_goi_yc = new DS_GD_CUOC_GOI_YEU_CAU();
            this.FillDataset(v_ds_gd_cuoc_goi_yc, " WHERE " + GD_CUOC_GOI_YEU_CAU.CALL_ID + " = '" + ip_str_call_id + "'");
            if (v_ds_gd_cuoc_goi_yc.GD_CUOC_GOI_YEU_CAU.Rows.Count > 0) return true;
            return false;
        }
        #endregion
    }
}
