///************************************************
/// Generated by: LinhDH
/// Date: 21/03/2014 03:14:18
/// Goal: Create User Service Class for GD_XU_LY_NOI_BO
///************************************************
/// <summary>
/// Create User Service Class for GD_XU_LY_NOI_BO
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_GD_XU_LY_NOI_BO : US_Object
	{
		private const string c_TableName = "GD_XU_LY_NOI_BO";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public decimal dcID_CAU_HOI 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_CAU_HOI", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_CAU_HOI"] = value;
			}
		}

		public bool IsID_CAU_HOINull()	{
			return pm_objDR.IsNull("ID_CAU_HOI");
		}

		public void SetID_CAU_HOINull() {
			pm_objDR["ID_CAU_HOI"] = System.Convert.DBNull;
		}

		public decimal dcID_CUOC_GOI 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_CUOC_GOI", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_CUOC_GOI"] = value;
			}
		}

		public bool IsID_CUOC_GOINull()	{
			return pm_objDR.IsNull("ID_CUOC_GOI");
		}

		public void SetID_CUOC_GOINull() {
			pm_objDR["ID_CUOC_GOI"] = System.Convert.DBNull;
		}

		public decimal dcID_USER_GOI 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_USER_GOI", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_USER_GOI"] = value;
			}
		}

		public bool IsID_USER_GOINull()	{
			return pm_objDR.IsNull("ID_USER_GOI");
		}

		public void SetID_USER_GOINull() {
			pm_objDR["ID_USER_GOI"] = System.Convert.DBNull;
		}

		public string strSO_DIEN_THOAI_GOI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "SO_DIEN_THOAI_GOI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["SO_DIEN_THOAI_GOI"] = value;
			}
		}

		public bool IsSO_DIEN_THOAI_GOINull() 
		{
			return pm_objDR.IsNull("SO_DIEN_THOAI_GOI");
		}

		public void SetSO_DIEN_THOAI_GOINull() {
			pm_objDR["SO_DIEN_THOAI_GOI"] = System.Convert.DBNull;
		}

		public decimal dcID_HANH_DONG_NOI_BO 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_HANH_DONG_NOI_BO", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_HANH_DONG_NOI_BO"] = value;
			}
		}

		public bool IsID_HANH_DONG_NOI_BONull()	{
			return pm_objDR.IsNull("ID_HANH_DONG_NOI_BO");
		}

		public void SetID_HANH_DONG_NOI_BONull() {
			pm_objDR["ID_HANH_DONG_NOI_BO"] = System.Convert.DBNull;
		}

		public decimal dcID_NGUOI_LIEN_QUAN 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_LIEN_QUAN", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_NGUOI_LIEN_QUAN"] = value;
			}
		}

		public bool IsID_NGUOI_LIEN_QUANNull()	{
			return pm_objDR.IsNull("ID_NGUOI_LIEN_QUAN");
		}

		public void SetID_NGUOI_LIEN_QUANNull() {
			pm_objDR["ID_NGUOI_LIEN_QUAN"] = System.Convert.DBNull;
		}

		public string strDUNG_SO_KHAC_YN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "DUNG_SO_KHAC_YN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["DUNG_SO_KHAC_YN"] = value;
			}
		}

		public bool IsDUNG_SO_KHAC_YNNull() 
		{
			return pm_objDR.IsNull("DUNG_SO_KHAC_YN");
		}

		public void SetDUNG_SO_KHAC_YNNull() {
			pm_objDR["DUNG_SO_KHAC_YN"] = System.Convert.DBNull;
		}

		public string strNOI_DUNG_TRAO_DOI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "NOI_DUNG_TRAO_DOI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["NOI_DUNG_TRAO_DOI"] = value;
			}
		}

		public bool IsNOI_DUNG_TRAO_DOINull() 
		{
			return pm_objDR.IsNull("NOI_DUNG_TRAO_DOI");
		}

		public void SetNOI_DUNG_TRAO_DOINull() {
			pm_objDR["NOI_DUNG_TRAO_DOI"] = System.Convert.DBNull;
		}

		public string strGHI_CHU 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["GHI_CHU"] = value;
			}
		}

		public bool IsGHI_CHUNull() 
		{
			return pm_objDR.IsNull("GHI_CHU");
		}

		public void SetGHI_CHUNull() {
			pm_objDR["GHI_CHU"] = System.Convert.DBNull;
		}

        public string strCALL_ID
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "CALL_ID", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["CALL_ID"] = value;
            }
        }

        public bool IsCALL_IDNull()
        {
            return pm_objDR.IsNull("CALL_ID");
        }

        public void SetCALL_IDNull()
        {
            pm_objDR["CALL_ID"] = System.Convert.DBNull;
        }

		public string strVOICE_CALL_LINK 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "VOICE_CALL_LINK", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["VOICE_CALL_LINK"] = value;
			}
		}

		public bool IsVOICE_CALL_LINKNull() 
		{
			return pm_objDR.IsNull("VOICE_CALL_LINK");
		}

		public void SetVOICE_CALL_LINKNull() {
			pm_objDR["VOICE_CALL_LINK"] = System.Convert.DBNull;
		}

		public DateTime datSTART_TIME
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "START_TIME", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["START_TIME"] = value;
			}
		}

		public bool IsSTART_TIMENull()
		{
			return pm_objDR.IsNull("START_TIME");
		}

		public void SetSTART_TIMENull()
		{
			pm_objDR["START_TIME"] = System.Convert.DBNull;
		}

		public DateTime datEND_TIME
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "END_TIME", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["END_TIME"] = value;
			}
		}

		public bool IsEND_TIMENull()
		{
			return pm_objDR.IsNull("END_TIME");
		}

		public void SetEND_TIMENull()
		{
			pm_objDR["END_TIME"] = System.Convert.DBNull;
		}

		public decimal dcSTATION_ID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "STATION_ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["STATION_ID"] = value;
			}
		}

		public bool IsSTATION_IDNull()	{
			return pm_objDR.IsNull("STATION_ID");
		}

		public void SetSTATION_IDNull() {
			pm_objDR["STATION_ID"] = System.Convert.DBNull;
		}

		public decimal dcDURATION 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "DURATION", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["DURATION"] = value;
			}
		}

		public bool IsDURATIONNull()	{
			return pm_objDR.IsNull("DURATION");
		}

		public void SetDURATIONNull() {
			pm_objDR["DURATION"] = System.Convert.DBNull;
		}

		public string strSTATUS 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "STATUS", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["STATUS"] = value;
			}
		}

		public bool IsSTATUSNull() 
		{
			return pm_objDR.IsNull("STATUS");
		}

		public void SetSTATUSNull() {
			pm_objDR["STATUS"] = System.Convert.DBNull;
		}

		public string strERROR_CODE 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "ERROR_CODE", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["ERROR_CODE"] = value;
			}
		}

		public bool IsERROR_CODENull() 
		{
			return pm_objDR.IsNull("ERROR_CODE");
		}

		public void SetERROR_CODENull() {
			pm_objDR["ERROR_CODE"] = System.Convert.DBNull;
		}

		public string strERROR_DESC 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "ERROR_DESC", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["ERROR_DESC"] = value;
			}
		}

		public bool IsERROR_DESCNull() 
		{
			return pm_objDR.IsNull("ERROR_DESC");
		}

		public void SetERROR_DESCNull() {
			pm_objDR["ERROR_DESC"] = System.Convert.DBNull;
		}

		public DateTime datDATETIME_RESPOND
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "DATETIME_RESPOND", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["DATETIME_RESPOND"] = value;
			}
		}

		public bool IsDATETIME_RESPONDNull()
		{
			return pm_objDR.IsNull("DATETIME_RESPOND");
		}

		public void SetDATETIME_RESPONDNull()
		{
			pm_objDR["DATETIME_RESPOND"] = System.Convert.DBNull;
		}

		public decimal dcRINGTIME 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "RINGTIME", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["RINGTIME"] = value;
			}
		}

		public bool IsRINGTIMENull()	{
			return pm_objDR.IsNull("RINGTIME");
		}

		public void SetRINGTIMENull() {
			pm_objDR["RINGTIME"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_GD_XU_LY_NOI_BO() 
		{
			pm_objDS = new DS_GD_XU_LY_NOI_BO();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_GD_XU_LY_NOI_BO(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_GD_XU_LY_NOI_BO(decimal i_dbID) 
		{
			pm_objDS = new DS_GD_XU_LY_NOI_BO();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

        #region Additional Funcitons
        public void load_ds_assign_qlht(DS_GD_XU_LY_NOI_BO op_ds ,decimal ip_dc_id_cau_hoi)
        {
            CStoredProc v_cstore = new CStoredProc("pr_GD_XU_LY_NOI_BO_Load_ds_assign_cau_hoi_cho_QLHT");

            v_cstore.addDecimalInputParam("@ID_CAU_HOI", ip_dc_id_cau_hoi);
            v_cstore.fillDataSetByCommand(this, op_ds);
        }
        #endregion
    }
}
