///************************************************
/// Generated by: LinhDH
/// Date: 17/05/2015 04:22:30
/// Goal: Create User Service Class for V_GD_DAT_HANG
///************************************************
/// <summary>
/// Create User Service Class for V_GD_DAT_HANG
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_V_GD_DAT_HANG : US_Object
	{
		private const string c_TableName = "V_GD_DAT_HANG";

        #region Public Properties
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public string strMA_DON_HANG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_DON_HANG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_DON_HANG"] = value;
            }
        }

        public bool IsMA_DON_HANGNull()
        {
            return pm_objDR.IsNull("MA_DON_HANG");
        }

        public void SetMA_DON_HANGNull()
        {
            pm_objDR["MA_DON_HANG"] = System.Convert.DBNull;
        }

        public string strUSER_NV_DAT_HANG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "USER_NV_DAT_HANG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["USER_NV_DAT_HANG"] = value;
            }
        }

        public bool IsUSER_NV_DAT_HANGNull()
        {
            return pm_objDR.IsNull("USER_NV_DAT_HANG");
        }

        public void SetUSER_NV_DAT_HANGNull()
        {
            pm_objDR["USER_NV_DAT_HANG"] = System.Convert.DBNull;
        }

        public decimal dcID_DON_VI
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DON_VI"] = value;
            }
        }

        public bool IsID_DON_VINull()
        {
            return pm_objDR.IsNull("ID_DON_VI");
        }

        public void SetID_DON_VINull()
        {
            pm_objDR["ID_DON_VI"] = System.Convert.DBNull;
        }

        public string strTEN_DON_VI
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_DON_VI"] = value;
            }
        }

        public bool IsTEN_DON_VINull()
        {
            return pm_objDR.IsNull("TEN_DON_VI");
        }

        public void SetTEN_DON_VINull()
        {
            pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
        }

        public string strDIEN_THOAI
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DIEN_THOAI", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DIEN_THOAI"] = value;
            }
        }

        public bool IsDIEN_THOAINull()
        {
            return pm_objDR.IsNull("DIEN_THOAI");
        }

        public void SetDIEN_THOAINull()
        {
            pm_objDR["DIEN_THOAI"] = System.Convert.DBNull;
        }

        public string strHO_TEN_USER_DAT_HANG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "HO_TEN_USER_DAT_HANG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["HO_TEN_USER_DAT_HANG"] = value;
            }
        }

        public bool IsHO_TEN_USER_DAT_HANGNull()
        {
            return pm_objDR.IsNull("HO_TEN_USER_DAT_HANG");
        }

        public void SetHO_TEN_USER_DAT_HANGNull()
        {
            pm_objDR["HO_TEN_USER_DAT_HANG"] = System.Convert.DBNull;
        }

        public DateTime datTHOI_GIAN_DAT_HANG
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "THOI_GIAN_DAT_HANG", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["THOI_GIAN_DAT_HANG"] = value;
            }
        }

        public bool IsTHOI_GIAN_DAT_HANGNull()
        {
            return pm_objDR.IsNull("THOI_GIAN_DAT_HANG");
        }

        public void SetTHOI_GIAN_DAT_HANGNull()
        {
            pm_objDR["THOI_GIAN_DAT_HANG"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_DV_YEU_CAU
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_DV_YEU_CAU", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_DV_YEU_CAU"] = value;
            }
        }

        public bool IsID_LOAI_DV_YEU_CAUNull()
        {
            return pm_objDR.IsNull("ID_LOAI_DV_YEU_CAU");
        }

        public void SetID_LOAI_DV_YEU_CAUNull()
        {
            pm_objDR["ID_LOAI_DV_YEU_CAU"] = System.Convert.DBNull;
        }

        public string strTEN_LOAI_DICH_VU
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_LOAI_DICH_VU", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_LOAI_DICH_VU"] = value;
            }
        }

        public bool IsTEN_LOAI_DICH_VUNull()
        {
            return pm_objDR.IsNull("TEN_LOAI_DICH_VU");
        }

        public void SetTEN_LOAI_DICH_VUNull()
        {
            pm_objDR["TEN_LOAI_DICH_VU"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_YEU_CAU_CHA
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_YEU_CAU_CHA", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_YEU_CAU_CHA"] = value;
            }
        }

        public bool IsID_LOAI_YEU_CAU_CHANull()
        {
            return pm_objDR.IsNull("ID_LOAI_YEU_CAU_CHA");
        }

        public void SetID_LOAI_YEU_CAU_CHANull()
        {
            pm_objDR["ID_LOAI_YEU_CAU_CHA"] = System.Convert.DBNull;
        }

        public string strTEN_LOAI_YC_CHA
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_LOAI_YC_CHA", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_LOAI_YC_CHA"] = value;
            }
        }

        public bool IsTEN_LOAI_YC_CHANull()
        {
            return pm_objDR.IsNull("TEN_LOAI_YC_CHA");
        }

        public void SetTEN_LOAI_YC_CHANull()
        {
            pm_objDR["TEN_LOAI_YC_CHA"] = System.Convert.DBNull;
        }

        public string strNOI_DUNG_DAT_HANG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NOI_DUNG_DAT_HANG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NOI_DUNG_DAT_HANG"] = value;
            }
        }

        public bool IsNOI_DUNG_DAT_HANGNull()
        {
            return pm_objDR.IsNull("NOI_DUNG_DAT_HANG");
        }

        public void SetNOI_DUNG_DAT_HANGNull()
        {
            pm_objDR["NOI_DUNG_DAT_HANG"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_THOI_GIAN_CAN_HOAN_THANH
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_THOI_GIAN_CAN_HOAN_THANH", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_THOI_GIAN_CAN_HOAN_THANH"] = value;
            }
        }

        public bool IsID_LOAI_THOI_GIAN_CAN_HOAN_THANHNull()
        {
            return pm_objDR.IsNull("ID_LOAI_THOI_GIAN_CAN_HOAN_THANH");
        }

        public void SetID_LOAI_THOI_GIAN_CAN_HOAN_THANHNull()
        {
            pm_objDR["ID_LOAI_THOI_GIAN_CAN_HOAN_THANH"] = System.Convert.DBNull;
        }

        public string strLOAI_THOI_GIAN_CAN_HOAN_THANH
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "LOAI_THOI_GIAN_CAN_HOAN_THANH", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["LOAI_THOI_GIAN_CAN_HOAN_THANH"] = value;
            }
        }

        public bool IsLOAI_THOI_GIAN_CAN_HOAN_THANHNull()
        {
            return pm_objDR.IsNull("LOAI_THOI_GIAN_CAN_HOAN_THANH");
        }

        public void SetLOAI_THOI_GIAN_CAN_HOAN_THANHNull()
        {
            pm_objDR["LOAI_THOI_GIAN_CAN_HOAN_THANH"] = System.Convert.DBNull;
        }

        public string strPHAN_HOI_TU_DVMC
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "PHAN_HOI_TU_DVMC", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["PHAN_HOI_TU_DVMC"] = value;
            }
        }

        public bool IsPHAN_HOI_TU_DVMCNull()
        {
            return pm_objDR.IsNull("PHAN_HOI_TU_DVMC");
        }

        public void SetPHAN_HOI_TU_DVMCNull()
        {
            pm_objDR["PHAN_HOI_TU_DVMC"] = System.Convert.DBNull;
        }

        public DateTime datTHOI_GIAN_HOAN_THANH
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "THOI_GIAN_HOAN_THANH", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["THOI_GIAN_HOAN_THANH"] = value;
            }
        }

        public bool IsTHOI_GIAN_HOAN_THANHNull()
        {
            return pm_objDR.IsNull("THOI_GIAN_HOAN_THANH");
        }

        public void SetTHOI_GIAN_HOAN_THANHNull()
        {
            pm_objDR["THOI_GIAN_HOAN_THANH"] = System.Convert.DBNull;
        }

        public decimal dcID_TRANG_THAI
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_TRANG_THAI"] = value;
            }
        }

        public bool IsID_TRANG_THAINull()
        {
            return pm_objDR.IsNull("ID_TRANG_THAI");
        }

        public void SetID_TRANG_THAINull()
        {
            pm_objDR["ID_TRANG_THAI"] = System.Convert.DBNull;
        }

        public string strTRANG_THAI_YC
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TRANG_THAI_YC", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TRANG_THAI_YC"] = value;
            }
        }

        public bool IsTRANG_THAI_YCNull()
        {
            return pm_objDR.IsNull("TRANG_THAI_YC");
        }

        public void SetTRANG_THAI_YCNull()
        {
            pm_objDR["TRANG_THAI_YC"] = System.Convert.DBNull;
        }

        public decimal dcID_DANH_GIA_TU_USER_DAT_HANG
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DANH_GIA_TU_USER_DAT_HANG", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DANH_GIA_TU_USER_DAT_HANG"] = value;
            }
        }

        public bool IsID_DANH_GIA_TU_USER_DAT_HANGNull()
        {
            return pm_objDR.IsNull("ID_DANH_GIA_TU_USER_DAT_HANG");
        }

        public void SetID_DANH_GIA_TU_USER_DAT_HANGNull()
        {
            pm_objDR["ID_DANH_GIA_TU_USER_DAT_HANG"] = System.Convert.DBNull;
        }

        public string strDANH_GIA_TU_USER_DAT_HANG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DANH_GIA_TU_USER_DAT_HANG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DANH_GIA_TU_USER_DAT_HANG"] = value;
            }
        }

        public bool IsDANH_GIA_TU_USER_DAT_HANGNull()
        {
            return pm_objDR.IsNull("DANH_GIA_TU_USER_DAT_HANG");
        }

        public void SetDANH_GIA_TU_USER_DAT_HANGNull()
        {
            pm_objDR["DANH_GIA_TU_USER_DAT_HANG"] = System.Convert.DBNull;
        }

        public string strY_KIEN_KHAC_TU_USER_DAT_HANG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "Y_KIEN_KHAC_TU_USER_DAT_HANG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["Y_KIEN_KHAC_TU_USER_DAT_HANG"] = value;
            }
        }

        public bool IsY_KIEN_KHAC_TU_USER_DAT_HANGNull()
        {
            return pm_objDR.IsNull("Y_KIEN_KHAC_TU_USER_DAT_HANG");
        }

        public void SetY_KIEN_KHAC_TU_USER_DAT_HANGNull()
        {
            pm_objDR["Y_KIEN_KHAC_TU_USER_DAT_HANG"] = System.Convert.DBNull;
        }

        public decimal dcID_NGUOI_NHAN_DAT_HANG
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_NHAN_DAT_HANG", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NGUOI_NHAN_DAT_HANG"] = value;
            }
        }

        public bool IsID_NGUOI_NHAN_DAT_HANGNull()
        {
            return pm_objDR.IsNull("ID_NGUOI_NHAN_DAT_HANG");
        }

        public void SetID_NGUOI_NHAN_DAT_HANGNull()
        {
            pm_objDR["ID_NGUOI_NHAN_DAT_HANG"] = System.Convert.DBNull;
        }

        public string strNGUOI_NHAN_DAT_HANG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_NHAN_DAT_HANG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_NHAN_DAT_HANG"] = value;
            }
        }

        public bool IsNGUOI_NHAN_DAT_HANGNull()
        {
            return pm_objDR.IsNull("NGUOI_NHAN_DAT_HANG");
        }

        public void SetNGUOI_NHAN_DAT_HANGNull()
        {
            pm_objDR["NGUOI_NHAN_DAT_HANG"] = System.Convert.DBNull;
        }

        public decimal dcID_NGUOI_XU_LY
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_XU_LY", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NGUOI_XU_LY"] = value;
            }
        }

        public bool IsID_NGUOI_XU_LYNull()
        {
            return pm_objDR.IsNull("ID_NGUOI_XU_LY");
        }

        public void SetID_NGUOI_XU_LYNull()
        {
            pm_objDR["ID_NGUOI_XU_LY"] = System.Convert.DBNull;
        }

        public string strNGUOI_XU_LY
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_XU_LY", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_XU_LY"] = value;
            }
        }

        public bool IsNGUOI_XU_LYNull()
        {
            return pm_objDR.IsNull("NGUOI_XU_LY");
        }

        public void SetNGUOI_XU_LYNull()
        {
            pm_objDR["NGUOI_XU_LY"] = System.Convert.DBNull;
        }

        public decimal dcID_NGUOI_TAO
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_TAO", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NGUOI_TAO"] = value;
            }
        }

        public bool IsID_NGUOI_TAONull()
        {
            return pm_objDR.IsNull("ID_NGUOI_TAO");
        }

        public void SetID_NGUOI_TAONull()
        {
            pm_objDR["ID_NGUOI_TAO"] = System.Convert.DBNull;
        }

        public DateTime datTHOI_GIAN_TAO
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "THOI_GIAN_TAO", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["THOI_GIAN_TAO"] = value;
            }
        }

        public bool IsTHOI_GIAN_TAONull()
        {
            return pm_objDR.IsNull("THOI_GIAN_TAO");
        }

        public void SetTHOI_GIAN_TAONull()
        {
            pm_objDR["THOI_GIAN_TAO"] = System.Convert.DBNull;
        }

        public string strLICH_SU_TRAO_DOI
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "LICH_SU_TRAO_DOI", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["LICH_SU_TRAO_DOI"] = value;
            }
        }

        public bool IsLICH_SU_TRAO_DOINull()
        {
            return pm_objDR.IsNull("LICH_SU_TRAO_DOI");
        }

        public void SetLICH_SU_TRAO_DOINull()
        {
            pm_objDR["LICH_SU_TRAO_DOI"] = System.Convert.DBNull;
        }

        public decimal dcID_NGUOI_SUA_CUOI
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_SUA_CUOI", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NGUOI_SUA_CUOI"] = value;
            }
        }

        public bool IsID_NGUOI_SUA_CUOINull()
        {
            return pm_objDR.IsNull("ID_NGUOI_SUA_CUOI");
        }

        public void SetID_NGUOI_SUA_CUOINull()
        {
            pm_objDR["ID_NGUOI_SUA_CUOI"] = System.Convert.DBNull;
        }

        public string strUSER_NGUOI_SUA_CUOI
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "USER_NGUOI_SUA_CUOI", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["USER_NGUOI_SUA_CUOI"] = value;
            }
        }

        public bool IsUSER_NGUOI_SUA_CUOINull()
        {
            return pm_objDR.IsNull("USER_NGUOI_SUA_CUOI");
        }

        public void SetUSER_NGUOI_SUA_CUOINull()
        {
            pm_objDR["USER_NGUOI_SUA_CUOI"] = System.Convert.DBNull;
        }

        public DateTime datTHOI_GIAN_SUA_CUOI
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "THOI_GIAN_SUA_CUOI", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["THOI_GIAN_SUA_CUOI"] = value;
            }
        }

        public bool IsTHOI_GIAN_SUA_CUOINull()
        {
            return pm_objDR.IsNull("THOI_GIAN_SUA_CUOI");
        }

        public void SetTHOI_GIAN_SUA_CUOINull()
        {
            pm_objDR["THOI_GIAN_SUA_CUOI"] = System.Convert.DBNull;
        }

        #endregion

		#region Init Functions
		public US_V_GD_DAT_HANG() 
		{
			pm_objDS = new DS_V_GD_DAT_HANG();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_V_GD_DAT_HANG(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_V_GD_DAT_HANG(decimal i_dbID) 
		{
			pm_objDS = new DS_V_GD_DAT_HANG();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

        #region Additional Functions
        public string get_ma_dat_hang_tiep_theo()
        {
            string v_output = "";
            CStoredProc v_cstore = new CStoredProc("pr_get_ma_don_hang");
            SqlParameter v_result = v_cstore.addNVarcharOutputParam("@MA_DON_HANG", v_output);
            v_cstore.ExecuteCommand(this);
            return v_result.Value.ToString();

        }
        public void load_ds_don_hang(DateTime ip_dat_tu_ngay
                                    , DateTime ip_dat_den_ngay
                                    , string ip_str_ma_don_hang
                                    , string ip_str_user_dat_hang
                                    , decimal ip_dc_id_thoi_han_hoan_thanh  
                                    , decimal ip_dc_id_trang_thai_don_hang
                                    , decimal ip_dc_id_nguoi_dung
                                    , string ip_str_da_danh_gia_yn
                                    , decimal ip_dc_id_nguoi_tiep_nhan
                                    , decimal ip_dc_id_nguoi_xu_ly
                                    , decimal ip_dc_id_loai_yeu_cau
                                    , decimal ip_dc_id_danh_gia_tu_khach_hang
                                    , DateTime ip_dat_hoan_thanh_tu_ngay
                                    , DateTime ip_dat_hoan_thanh_den_ngay
                                    , DS_V_GD_DAT_HANG op_ds)
        {
            CStoredProc v_cstore = new CStoredProc("pr_V_GD_DAT_HANG_load_ds_don_hang_v30");
            v_cstore.addDatetimeInputParam("@TU_NGAY", ip_dat_tu_ngay);
            v_cstore.addDatetimeInputParam("@DEN_NGAY", ip_dat_den_ngay);
            v_cstore.addNVarcharInputParam("@MA_DON_HANG", ip_str_ma_don_hang);
            v_cstore.addNVarcharInputParam("@USER_DAT_HANG", ip_str_user_dat_hang);
            v_cstore.addDecimalInputParam("@ID_THOI_HAN", ip_dc_id_thoi_han_hoan_thanh);
            v_cstore.addDecimalInputParam("@ID_TRANG_THAI", ip_dc_id_trang_thai_don_hang);
            v_cstore.addDecimalInputParam("@ID_USER", ip_dc_id_nguoi_dung);
            v_cstore.addDecimalInputParam("@ID_NGUOI_XU_LY", ip_dc_id_nguoi_xu_ly);
            v_cstore.addDecimalInputParam("@ID_NGUOI_TIEP_NHAN", ip_dc_id_nguoi_tiep_nhan);
            v_cstore.addDecimalInputParam("@ID_LOAI_YEU_CAU", ip_dc_id_loai_yeu_cau);
            v_cstore.addDecimalInputParam("@ID_DANH_GIA_TU_KHACH_HANG", ip_dc_id_danh_gia_tu_khach_hang);
            v_cstore.addNVarcharInputParam("@DA_DANH_GIA_YN", ip_str_da_danh_gia_yn);
            v_cstore.addDatetimeInputParam("@HOAN_THANH_TU_NGAY", ip_dat_hoan_thanh_tu_ngay);
            v_cstore.addDatetimeInputParam("@HOAN_THANH_DEN_NGAY", ip_dat_hoan_thanh_den_ngay);
            v_cstore.fillDataSetByCommand(this, op_ds);
        }
        public void load_dat_hang_by_ma(string ip_str_ma_dat_hang
                                    , string ip_str_username
                                    , DS_V_GD_DAT_HANG op_ds)
        {
            CStoredProc v_cstore = new CStoredProc("pr_V_GD_DAT_HANG_load_dat_hang_by_ma");
            v_cstore.addNVarcharInputParam("@MA_DAT_HANG", ip_str_ma_dat_hang);
            v_cstore.addNVarcharInputParam("@USERNAME", ip_str_username);
            v_cstore.fillDataSetByCommand(this, op_ds);
        }

        public void danh_gia_don_hang(decimal ip_id_don_hang, decimal ip_dc_id_danh_gia, string ip_str_y_kien_khac)
        {
            CStoredProc v_cstore = new CStoredProc("pr_V_GD_DAT_HANG_danh_gia_don_hang");
            v_cstore.addDecimalInputParam("@ID_DON_HANG", ip_id_don_hang);
            v_cstore.addDecimalInputParam("@ID_DANH_GIA", ip_dc_id_danh_gia);
            v_cstore.addNVarcharInputParam("@Y_KIEN_KHAC", ip_str_y_kien_khac);
            v_cstore.ExecuteCommand(this);
        }
        public void cap_nhat_don_hang()
        {
            CStoredProc v_cstore = new CStoredProc("pr_V_GD_DAT_HANG_cap_nhat_don_hang");
            v_cstore.addDecimalInputParam("@ID_DON_HANG", this.dcID);
            v_cstore.addDecimalInputParam("@ID_TRANG_THAI", this.dcID_TRANG_THAI);
            v_cstore.addNVarcharInputParam("@PHAN_HOI_TU_DVMC", this.strPHAN_HOI_TU_DVMC);
            v_cstore.addDecimalInputParam("@ID_LOAI_THOI_GIAN_CAN_HOAN_THANH", this.dcID_LOAI_THOI_GIAN_CAN_HOAN_THANH);
            v_cstore.addNVarcharInputParam("@LICH_SU_TRAO_DOI", this.strLICH_SU_TRAO_DOI);
            v_cstore.addDecimalInputParam("@ID_NGUOI_SUA_CUOI", this.dcID_NGUOI_SUA_CUOI);
            v_cstore.addNVarcharInputParam("@USER_NGUOI_XU_LY", this.strNGUOI_XU_LY);
            v_cstore.ExecuteCommand(this);
        }
        #endregion
    }
}
