///************************************************
/// Generated by: vannd
/// Date: 09/08/2015 07:31:04
/// Goal: Create User Service Class for V_GD_DIEU_PHOI_LAI
///************************************************
/// <summary>
/// Create User Service Class for V_GD_DIEU_PHOI_LAI
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_V_GD_DIEU_PHOI_LAI : US_Object
	{
		private const string c_TableName = "V_GD_DIEU_PHOI_LAI";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public decimal dcID_GD_DAT_HANG 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_GD_DAT_HANG", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_GD_DAT_HANG"] = value;
			}
		}

		public bool IsID_GD_DAT_HANGNull()	{
			return pm_objDR.IsNull("ID_GD_DAT_HANG");
		}

		public void SetID_GD_DAT_HANGNull() {
			pm_objDR["ID_GD_DAT_HANG"] = System.Convert.DBNull;
		}

		public decimal dcID_NGUOI_NHAN_THAO_TAC 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_NHAN_THAO_TAC", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_NGUOI_NHAN_THAO_TAC"] = value;
			}
		}

		public bool IsID_NGUOI_NHAN_THAO_TACNull()	{
			return pm_objDR.IsNull("ID_NGUOI_NHAN_THAO_TAC");
		}

		public void SetID_NGUOI_NHAN_THAO_TACNull() {
			pm_objDR["ID_NGUOI_NHAN_THAO_TAC"] = System.Convert.DBNull;
		}

		public decimal dcBO 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "BO", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["BO"] = value;
			}
		}

		public bool IsBONull()	{
			return pm_objDR.IsNull("BO");
		}

		public void SetBONull() {
			pm_objDR["BO"] = System.Convert.DBNull;
		}

		public string strGHI_CHU 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["GHI_CHU"] = value;
			}
		}

		public bool IsGHI_CHUNull() 
		{
			return pm_objDR.IsNull("GHI_CHU");
		}

		public void SetGHI_CHUNull() {
			pm_objDR["GHI_CHU"] = System.Convert.DBNull;
		}

		public string strHO_TEN_USER_DAT_HANG 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "HO_TEN_USER_DAT_HANG", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["HO_TEN_USER_DAT_HANG"] = value;
			}
		}

		public bool IsHO_TEN_USER_DAT_HANGNull() 
		{
			return pm_objDR.IsNull("HO_TEN_USER_DAT_HANG");
		}

		public void SetHO_TEN_USER_DAT_HANGNull() {
			pm_objDR["HO_TEN_USER_DAT_HANG"] = System.Convert.DBNull;
		}

		public string strNOI_DUNG_DAT_HANG 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "NOI_DUNG_DAT_HANG", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["NOI_DUNG_DAT_HANG"] = value;
			}
		}

		public bool IsNOI_DUNG_DAT_HANGNull() 
		{
			return pm_objDR.IsNull("NOI_DUNG_DAT_HANG");
		}

		public void SetNOI_DUNG_DAT_HANGNull() {
			pm_objDR["NOI_DUNG_DAT_HANG"] = System.Convert.DBNull;
		}

		public DateTime datTHOI_GIAN_DAT_HANG
		{
			get   
			{
				return CNull.RowNVLDate(pm_objDR, "THOI_GIAN_DAT_HANG", IPConstants.c_DefaultDate);
			}
			set   
			{
				pm_objDR["THOI_GIAN_DAT_HANG"] = value;
			}
		}

		public bool IsTHOI_GIAN_DAT_HANGNull()
		{
			return pm_objDR.IsNull("THOI_GIAN_DAT_HANG");
		}

		public void SetTHOI_GIAN_DAT_HANGNull()
		{
			pm_objDR["THOI_GIAN_DAT_HANG"] = System.Convert.DBNull;
		}

		public string strTEN_YEU_CAU 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_YEU_CAU", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_YEU_CAU"] = value;
			}
		}

		public bool IsTEN_YEU_CAUNull() 
		{
			return pm_objDR.IsNull("TEN_YEU_CAU");
		}

		public void SetTEN_YEU_CAUNull() {
			pm_objDR["TEN_YEU_CAU"] = System.Convert.DBNull;
		}

		public decimal dcID_DV_YEU_CAU 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_DV_YEU_CAU", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_DV_YEU_CAU"] = value;
			}
		}

		public bool IsID_DV_YEU_CAUNull()	{
			return pm_objDR.IsNull("ID_DV_YEU_CAU");
		}

		public void SetID_DV_YEU_CAUNull() {
			pm_objDR["ID_DV_YEU_CAU"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_V_GD_DIEU_PHOI_LAI() 
		{
            //pm_objDS = new DS_V_GD_DIEU_PHOI_LAI();
            //pm_strTableName = c_TableName;
            //pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_V_GD_DIEU_PHOI_LAI(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_V_GD_DIEU_PHOI_LAI(decimal i_dbID) 
		{
            //pm_objDS = new DS_V_GD_DIEU_PHOI_LAI();
            //pm_strTableName = c_TableName;
            //IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            //v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            //SqlCommand v_cmdSQL;
            //v_cmdSQL = v_objMkCmd.getSelectCmd();
            //this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            //pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
