///************************************************
/// Generated by: LinhDH
/// Date: 17/05/2015 10:05:49
/// Goal: Create Form for V_GD_DAT_HANG
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;

using IPCOREDS;
using IPCOREUS;
using IPCOREDS.CDBNames;

using C1.Win.C1FlexGrid;
using IP.Core.IPSystemAdmin;
using TOSApp.ChucNang;

namespace TOSApp
{

	public class f200_ds_dat_hang : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
		private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
		internal SIS.Controls.Button.SiSButton m_cmd_delete;
		internal SIS.Controls.Button.SiSButton m_cmd_update;
		internal SIS.Controls.Button.SiSButton m_cmd_insert;
        internal SIS.Controls.Button.SiSButton m_cmd_exit;
        private Label m_lbl_header;
        private Panel m_pnl_search_area;
        private Label label1;
        private TextBox m_txt_nguoi_dat_hang;
        private Label m_lbl_lich_nhac_viec_tu;
        private Label m_lbl_lich_nhac_viec_den;
        private DateTimePicker m_dat_from_date;
        private DateTimePicker m_dat_to_date;
        private ComboBox m_cbo_tho_han_xu_ly;
        private Label label2;
        private ComboBox m_cbo_trang_thai_don_hang;
        private Label label3;
        private Label label4;
        private TextBox m_txt_ma_don_hang;
        private Button m_cmd_tim_kiem;
        internal SIS.Controls.Button.SiSButton m_cmd_hoan_thanh;
        private Label label5;
        private RadioButton m_rdb_danh_gia_all;
        private RadioButton m_rdb_danh_gia_no;
        private RadioButton m_rdb_danh_gia_yes;
        private Label label6;
        private ComboBox m_cbo_danh_gia_tu_khach_hang;
        private ComboBox m_cbo_nguoi_nhan_dat_hang;
        private Label label7;
        private ComboBox m_cbo_nguoi_xu_ly;
        private Label label8;
        private ComboBox m_cbo_loai_yeu_cau;
        private Label label9;
        private Label m_lbl_so_luong_dat_hang;
        internal SIS.Controls.Button.SiSButton m_cmd_danh_gia_cua_KH;
        private Label label11;
        private Label label10;
        private DateTimePicker m_dat_time_hoan_thanh_tu_ngay;
        private DateTimePicker m_dat_time_hoan_thanh_den_ngay;
		private System.ComponentModel.IContainer components;

		public f200_ds_dat_hang()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f200_ds_dat_hang));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_danh_gia_cua_KH = new SIS.Controls.Button.SiSButton();
            this.m_lbl_so_luong_dat_hang = new System.Windows.Forms.Label();
            this.m_cmd_hoan_thanh = new SIS.Controls.Button.SiSButton();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.m_lbl_header = new System.Windows.Forms.Label();
            this.m_pnl_search_area = new System.Windows.Forms.Panel();
            this.m_cbo_nguoi_xu_ly = new System.Windows.Forms.ComboBox();
            this.m_cbo_nguoi_nhan_dat_hang = new System.Windows.Forms.ComboBox();
            this.m_rdb_danh_gia_no = new System.Windows.Forms.RadioButton();
            this.m_rdb_danh_gia_yes = new System.Windows.Forms.RadioButton();
            this.m_rdb_danh_gia_all = new System.Windows.Forms.RadioButton();
            this.m_cmd_tim_kiem = new System.Windows.Forms.Button();
            this.label4 = new System.Windows.Forms.Label();
            this.m_cbo_loai_yeu_cau = new System.Windows.Forms.ComboBox();
            this.m_cbo_danh_gia_tu_khach_hang = new System.Windows.Forms.ComboBox();
            this.m_cbo_trang_thai_don_hang = new System.Windows.Forms.ComboBox();
            this.m_cbo_tho_han_xu_ly = new System.Windows.Forms.ComboBox();
            this.label11 = new System.Windows.Forms.Label();
            this.m_lbl_lich_nhac_viec_tu = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.m_lbl_lich_nhac_viec_den = new System.Windows.Forms.Label();
            this.m_dat_time_hoan_thanh_tu_ngay = new System.Windows.Forms.DateTimePicker();
            this.m_dat_from_date = new System.Windows.Forms.DateTimePicker();
            this.label9 = new System.Windows.Forms.Label();
            this.m_dat_time_hoan_thanh_den_ngay = new System.Windows.Forms.DateTimePicker();
            this.m_dat_to_date = new System.Windows.Forms.DateTimePicker();
            this.label6 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.m_txt_ma_don_hang = new System.Windows.Forms.TextBox();
            this.m_txt_nguoi_dat_hang = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.m_pnl_search_area.SuspendLayout();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_danh_gia_cua_KH);
            this.m_pnl_out_place_dm.Controls.Add(this.m_lbl_so_luong_dat_hang);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_hoan_thanh);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 493);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(968, 39);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_danh_gia_cua_KH
            // 
            this.m_cmd_danh_gia_cua_KH.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_danh_gia_cua_KH.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_danh_gia_cua_KH.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_danh_gia_cua_KH.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_danh_gia_cua_KH.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_danh_gia_cua_KH.ImageIndex = 0;
            this.m_cmd_danh_gia_cua_KH.ImageList = this.ImageList;
            this.m_cmd_danh_gia_cua_KH.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_danh_gia_cua_KH.Name = "m_cmd_danh_gia_cua_KH";
            this.m_cmd_danh_gia_cua_KH.Size = new System.Drawing.Size(169, 31);
            this.m_cmd_danh_gia_cua_KH.TabIndex = 24;
            this.m_cmd_danh_gia_cua_KH.Text = "Đánh giá của Khách hàng";
            // 
            // m_lbl_so_luong_dat_hang
            // 
            this.m_lbl_so_luong_dat_hang.AutoSize = true;
            this.m_lbl_so_luong_dat_hang.Font = new System.Drawing.Font("Arial", 9F);
            this.m_lbl_so_luong_dat_hang.Location = new System.Drawing.Point(12, 13);
            this.m_lbl_so_luong_dat_hang.Name = "m_lbl_so_luong_dat_hang";
            this.m_lbl_so_luong_dat_hang.Size = new System.Drawing.Size(16, 15);
            this.m_lbl_so_luong_dat_hang.TabIndex = 23;
            this.m_lbl_so_luong_dat_hang.Text = "...";
            // 
            // m_cmd_hoan_thanh
            // 
            this.m_cmd_hoan_thanh.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_hoan_thanh.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_hoan_thanh.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_hoan_thanh.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_hoan_thanh.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_hoan_thanh.ImageIndex = 13;
            this.m_cmd_hoan_thanh.ImageList = this.ImageList;
            this.m_cmd_hoan_thanh.Location = new System.Drawing.Point(395, 4);
            this.m_cmd_hoan_thanh.Name = "m_cmd_hoan_thanh";
            this.m_cmd_hoan_thanh.Size = new System.Drawing.Size(139, 31);
            this.m_cmd_hoan_thanh.TabIndex = 22;
            this.m_cmd_hoan_thanh.Text = "Hoàn thành đơn hàng";
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(534, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(128, 31);
            this.m_cmd_insert.TabIndex = 12;
            this.m_cmd_insert.Text = "Tạo mới đơn hàng";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(662, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(126, 31);
            this.m_cmd_update.TabIndex = 13;
            this.m_cmd_update.Text = "Cập nhật đơn hàng";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(788, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 31);
            this.m_cmd_delete.TabIndex = 14;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(876, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 31);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_fg.Location = new System.Drawing.Point(0, 199);
            this.m_fg.Name = "m_fg";
            this.m_fg.Rows.Count = 1;
            this.m_fg.Size = new System.Drawing.Size(968, 294);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            // 
            // m_lbl_header
            // 
            this.m_lbl_header.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_lbl_header.Font = new System.Drawing.Font("Arial", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_header.ForeColor = System.Drawing.Color.Maroon;
            this.m_lbl_header.Location = new System.Drawing.Point(0, 0);
            this.m_lbl_header.Name = "m_lbl_header";
            this.m_lbl_header.Size = new System.Drawing.Size(968, 40);
            this.m_lbl_header.TabIndex = 25;
            this.m_lbl_header.Text = "F200 - Danh sách các đặt hàng";
            this.m_lbl_header.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // m_pnl_search_area
            // 
            this.m_pnl_search_area.Controls.Add(this.m_cbo_nguoi_xu_ly);
            this.m_pnl_search_area.Controls.Add(this.m_cbo_nguoi_nhan_dat_hang);
            this.m_pnl_search_area.Controls.Add(this.m_rdb_danh_gia_no);
            this.m_pnl_search_area.Controls.Add(this.m_rdb_danh_gia_yes);
            this.m_pnl_search_area.Controls.Add(this.m_rdb_danh_gia_all);
            this.m_pnl_search_area.Controls.Add(this.m_cmd_tim_kiem);
            this.m_pnl_search_area.Controls.Add(this.label4);
            this.m_pnl_search_area.Controls.Add(this.m_cbo_loai_yeu_cau);
            this.m_pnl_search_area.Controls.Add(this.m_cbo_danh_gia_tu_khach_hang);
            this.m_pnl_search_area.Controls.Add(this.m_cbo_trang_thai_don_hang);
            this.m_pnl_search_area.Controls.Add(this.m_cbo_tho_han_xu_ly);
            this.m_pnl_search_area.Controls.Add(this.label11);
            this.m_pnl_search_area.Controls.Add(this.m_lbl_lich_nhac_viec_tu);
            this.m_pnl_search_area.Controls.Add(this.label10);
            this.m_pnl_search_area.Controls.Add(this.m_lbl_lich_nhac_viec_den);
            this.m_pnl_search_area.Controls.Add(this.m_dat_time_hoan_thanh_tu_ngay);
            this.m_pnl_search_area.Controls.Add(this.m_dat_from_date);
            this.m_pnl_search_area.Controls.Add(this.label9);
            this.m_pnl_search_area.Controls.Add(this.m_dat_time_hoan_thanh_den_ngay);
            this.m_pnl_search_area.Controls.Add(this.m_dat_to_date);
            this.m_pnl_search_area.Controls.Add(this.label6);
            this.m_pnl_search_area.Controls.Add(this.label3);
            this.m_pnl_search_area.Controls.Add(this.m_txt_ma_don_hang);
            this.m_pnl_search_area.Controls.Add(this.m_txt_nguoi_dat_hang);
            this.m_pnl_search_area.Controls.Add(this.label2);
            this.m_pnl_search_area.Controls.Add(this.label8);
            this.m_pnl_search_area.Controls.Add(this.label7);
            this.m_pnl_search_area.Controls.Add(this.label5);
            this.m_pnl_search_area.Controls.Add(this.label1);
            this.m_pnl_search_area.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_pnl_search_area.Location = new System.Drawing.Point(0, 40);
            this.m_pnl_search_area.Name = "m_pnl_search_area";
            this.m_pnl_search_area.Size = new System.Drawing.Size(968, 159);
            this.m_pnl_search_area.TabIndex = 26;
            // 
            // m_cbo_nguoi_xu_ly
            // 
            this.m_cbo_nguoi_xu_ly.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.m_cbo_nguoi_xu_ly.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.m_cbo_nguoi_xu_ly.FormattingEnabled = true;
            this.m_cbo_nguoi_xu_ly.Location = new System.Drawing.Point(398, 98);
            this.m_cbo_nguoi_xu_ly.Name = "m_cbo_nguoi_xu_ly";
            this.m_cbo_nguoi_xu_ly.Size = new System.Drawing.Size(143, 22);
            this.m_cbo_nguoi_xu_ly.TabIndex = 7;
            // 
            // m_cbo_nguoi_nhan_dat_hang
            // 
            this.m_cbo_nguoi_nhan_dat_hang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.m_cbo_nguoi_nhan_dat_hang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.m_cbo_nguoi_nhan_dat_hang.FormattingEnabled = true;
            this.m_cbo_nguoi_nhan_dat_hang.Location = new System.Drawing.Point(152, 98);
            this.m_cbo_nguoi_nhan_dat_hang.Name = "m_cbo_nguoi_nhan_dat_hang";
            this.m_cbo_nguoi_nhan_dat_hang.Size = new System.Drawing.Size(147, 22);
            this.m_cbo_nguoi_nhan_dat_hang.TabIndex = 6;
            // 
            // m_rdb_danh_gia_no
            // 
            this.m_rdb_danh_gia_no.AutoSize = true;
            this.m_rdb_danh_gia_no.Location = new System.Drawing.Point(310, 129);
            this.m_rdb_danh_gia_no.Name = "m_rdb_danh_gia_no";
            this.m_rdb_danh_gia_no.Size = new System.Drawing.Size(95, 18);
            this.m_rdb_danh_gia_no.TabIndex = 34;
            this.m_rdb_danh_gia_no.Text = "Chưa đánh giá";
            this.m_rdb_danh_gia_no.UseVisualStyleBackColor = true;
            // 
            // m_rdb_danh_gia_yes
            // 
            this.m_rdb_danh_gia_yes.AutoSize = true;
            this.m_rdb_danh_gia_yes.Location = new System.Drawing.Point(218, 129);
            this.m_rdb_danh_gia_yes.Name = "m_rdb_danh_gia_yes";
            this.m_rdb_danh_gia_yes.Size = new System.Drawing.Size(83, 18);
            this.m_rdb_danh_gia_yes.TabIndex = 34;
            this.m_rdb_danh_gia_yes.Text = "Đã đánh giá";
            this.m_rdb_danh_gia_yes.UseVisualStyleBackColor = true;
            // 
            // m_rdb_danh_gia_all
            // 
            this.m_rdb_danh_gia_all.AutoSize = true;
            this.m_rdb_danh_gia_all.Checked = true;
            this.m_rdb_danh_gia_all.Location = new System.Drawing.Point(152, 129);
            this.m_rdb_danh_gia_all.Name = "m_rdb_danh_gia_all";
            this.m_rdb_danh_gia_all.Size = new System.Drawing.Size(55, 18);
            this.m_rdb_danh_gia_all.TabIndex = 33;
            this.m_rdb_danh_gia_all.TabStop = true;
            this.m_rdb_danh_gia_all.Text = "Tất cả";
            this.m_rdb_danh_gia_all.UseVisualStyleBackColor = true;
            // 
            // m_cmd_tim_kiem
            // 
            this.m_cmd_tim_kiem.Image = ((System.Drawing.Image)(resources.GetObject("m_cmd_tim_kiem.Image")));
            this.m_cmd_tim_kiem.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_tim_kiem.Location = new System.Drawing.Point(873, 46);
            this.m_cmd_tim_kiem.Name = "m_cmd_tim_kiem";
            this.m_cmd_tim_kiem.Size = new System.Drawing.Size(80, 47);
            this.m_cmd_tim_kiem.TabIndex = 32;
            this.m_cmd_tim_kiem.Text = "     Lọc";
            this.m_cmd_tim_kiem.UseVisualStyleBackColor = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(77, 69);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(70, 14);
            this.label4.TabIndex = 31;
            this.label4.Text = "Mã đơn hàng";
            // 
            // m_cbo_loai_yeu_cau
            // 
            this.m_cbo_loai_yeu_cau.DisplayMember = "Tất cả";
            this.m_cbo_loai_yeu_cau.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_loai_yeu_cau.FormattingEnabled = true;
            this.m_cbo_loai_yeu_cau.Location = new System.Drawing.Point(675, 96);
            this.m_cbo_loai_yeu_cau.Name = "m_cbo_loai_yeu_cau";
            this.m_cbo_loai_yeu_cau.Size = new System.Drawing.Size(183, 22);
            this.m_cbo_loai_yeu_cau.TabIndex = 8;
            this.m_cbo_loai_yeu_cau.ValueMember = "Tất cả";
            // 
            // m_cbo_danh_gia_tu_khach_hang
            // 
            this.m_cbo_danh_gia_tu_khach_hang.DisplayMember = "Tất cả";
            this.m_cbo_danh_gia_tu_khach_hang.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_danh_gia_tu_khach_hang.FormattingEnabled = true;
            this.m_cbo_danh_gia_tu_khach_hang.Location = new System.Drawing.Point(675, 123);
            this.m_cbo_danh_gia_tu_khach_hang.Name = "m_cbo_danh_gia_tu_khach_hang";
            this.m_cbo_danh_gia_tu_khach_hang.Size = new System.Drawing.Size(183, 22);
            this.m_cbo_danh_gia_tu_khach_hang.TabIndex = 9;
            this.m_cbo_danh_gia_tu_khach_hang.ValueMember = "Tất cả";
            // 
            // m_cbo_trang_thai_don_hang
            // 
            this.m_cbo_trang_thai_don_hang.DisplayMember = "Tất cả";
            this.m_cbo_trang_thai_don_hang.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_trang_thai_don_hang.FormattingEnabled = true;
            this.m_cbo_trang_thai_don_hang.Location = new System.Drawing.Point(675, 66);
            this.m_cbo_trang_thai_don_hang.Name = "m_cbo_trang_thai_don_hang";
            this.m_cbo_trang_thai_don_hang.Size = new System.Drawing.Size(183, 22);
            this.m_cbo_trang_thai_don_hang.TabIndex = 5;
            this.m_cbo_trang_thai_don_hang.ValueMember = "Tất cả";
            // 
            // m_cbo_tho_han_xu_ly
            // 
            this.m_cbo_tho_han_xu_ly.DisplayMember = "Tất cả";
            this.m_cbo_tho_han_xu_ly.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_tho_han_xu_ly.FormattingEnabled = true;
            this.m_cbo_tho_han_xu_ly.Location = new System.Drawing.Point(675, 14);
            this.m_cbo_tho_han_xu_ly.Name = "m_cbo_tho_han_xu_ly";
            this.m_cbo_tho_han_xu_ly.Size = new System.Drawing.Size(183, 22);
            this.m_cbo_tho_han_xu_ly.TabIndex = 2;
            this.m_cbo_tho_han_xu_ly.ValueMember = "Tất cả";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(2, 44);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(148, 14);
            this.label11.TabIndex = 26;
            this.label11.Text = "Thời gian hoàn thành từ ngày";
            // 
            // m_lbl_lich_nhac_viec_tu
            // 
            this.m_lbl_lich_nhac_viec_tu.AutoSize = true;
            this.m_lbl_lich_nhac_viec_tu.Location = new System.Drawing.Point(13, 16);
            this.m_lbl_lich_nhac_viec_tu.Name = "m_lbl_lich_nhac_viec_tu";
            this.m_lbl_lich_nhac_viec_tu.Size = new System.Drawing.Size(136, 14);
            this.m_lbl_lich_nhac_viec_tu.TabIndex = 26;
            this.m_lbl_lich_nhac_viec_tu.Text = "Thời gian đặt hàng từ ngày";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Enabled = false;
            this.label10.Location = new System.Drawing.Point(339, 45);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(54, 14);
            this.label10.TabIndex = 27;
            this.label10.Text = "Đến ngày";
            // 
            // m_lbl_lich_nhac_viec_den
            // 
            this.m_lbl_lich_nhac_viec_den.AutoSize = true;
            this.m_lbl_lich_nhac_viec_den.Enabled = false;
            this.m_lbl_lich_nhac_viec_den.Location = new System.Drawing.Point(339, 17);
            this.m_lbl_lich_nhac_viec_den.Name = "m_lbl_lich_nhac_viec_den";
            this.m_lbl_lich_nhac_viec_den.Size = new System.Drawing.Size(54, 14);
            this.m_lbl_lich_nhac_viec_den.TabIndex = 27;
            this.m_lbl_lich_nhac_viec_den.Text = "Đến ngày";
            // 
            // m_dat_time_hoan_thanh_tu_ngay
            // 
            this.m_dat_time_hoan_thanh_tu_ngay.Checked = false;
            this.m_dat_time_hoan_thanh_tu_ngay.CustomFormat = "dd/MM/yyyy HH:mm:ss";
            this.m_dat_time_hoan_thanh_tu_ngay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_time_hoan_thanh_tu_ngay.Location = new System.Drawing.Point(152, 41);
            this.m_dat_time_hoan_thanh_tu_ngay.Name = "m_dat_time_hoan_thanh_tu_ngay";
            this.m_dat_time_hoan_thanh_tu_ngay.ShowCheckBox = true;
            this.m_dat_time_hoan_thanh_tu_ngay.Size = new System.Drawing.Size(147, 20);
            this.m_dat_time_hoan_thanh_tu_ngay.TabIndex = 0;
            this.m_dat_time_hoan_thanh_tu_ngay.Value = new System.DateTime(2015, 5, 17, 0, 0, 0, 0);
            // 
            // m_dat_from_date
            // 
            this.m_dat_from_date.CustomFormat = "dd/MM/yyyy HH:mm:ss";
            this.m_dat_from_date.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_from_date.Location = new System.Drawing.Point(152, 13);
            this.m_dat_from_date.Name = "m_dat_from_date";
            this.m_dat_from_date.ShowCheckBox = true;
            this.m_dat_from_date.Size = new System.Drawing.Size(147, 20);
            this.m_dat_from_date.TabIndex = 0;
            this.m_dat_from_date.Value = new System.DateTime(2015, 5, 17, 0, 0, 0, 0);
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(602, 100);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(69, 14);
            this.label9.TabIndex = 14;
            this.label9.Text = "Loại yêu cầu";
            // 
            // m_dat_time_hoan_thanh_den_ngay
            // 
            this.m_dat_time_hoan_thanh_den_ngay.Checked = false;
            this.m_dat_time_hoan_thanh_den_ngay.CustomFormat = "dd/MM/yyyy HH:mm:ss";
            this.m_dat_time_hoan_thanh_den_ngay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_time_hoan_thanh_den_ngay.Location = new System.Drawing.Point(398, 41);
            this.m_dat_time_hoan_thanh_den_ngay.Name = "m_dat_time_hoan_thanh_den_ngay";
            this.m_dat_time_hoan_thanh_den_ngay.ShowCheckBox = true;
            this.m_dat_time_hoan_thanh_den_ngay.Size = new System.Drawing.Size(143, 20);
            this.m_dat_time_hoan_thanh_den_ngay.TabIndex = 1;
            this.m_dat_time_hoan_thanh_den_ngay.Value = new System.DateTime(2015, 5, 17, 0, 0, 0, 0);
            // 
            // m_dat_to_date
            // 
            this.m_dat_to_date.CustomFormat = "dd/MM/yyyy HH:mm:ss";
            this.m_dat_to_date.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_to_date.Location = new System.Drawing.Point(398, 13);
            this.m_dat_to_date.Name = "m_dat_to_date";
            this.m_dat_to_date.ShowCheckBox = true;
            this.m_dat_to_date.Size = new System.Drawing.Size(143, 20);
            this.m_dat_to_date.TabIndex = 1;
            this.m_dat_to_date.Value = new System.DateTime(2015, 5, 17, 0, 0, 0, 0);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(548, 126);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(122, 14);
            this.label6.TabIndex = 14;
            this.label6.Text = "Đánh giá từ khách hàng";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(566, 70);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(104, 14);
            this.label3.TabIndex = 14;
            this.label3.Text = "Trạng thái đơn hàng";
            // 
            // m_txt_ma_don_hang
            // 
            this.m_txt_ma_don_hang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.m_txt_ma_don_hang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.m_txt_ma_don_hang.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.m_txt_ma_don_hang.Location = new System.Drawing.Point(152, 67);
            this.m_txt_ma_don_hang.Name = "m_txt_ma_don_hang";
            this.m_txt_ma_don_hang.Size = new System.Drawing.Size(147, 20);
            this.m_txt_ma_don_hang.TabIndex = 3;
            // 
            // m_txt_nguoi_dat_hang
            // 
            this.m_txt_nguoi_dat_hang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.m_txt_nguoi_dat_hang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.m_txt_nguoi_dat_hang.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.m_txt_nguoi_dat_hang.Location = new System.Drawing.Point(398, 67);
            this.m_txt_nguoi_dat_hang.Name = "m_txt_nguoi_dat_hang";
            this.m_txt_nguoi_dat_hang.Size = new System.Drawing.Size(143, 20);
            this.m_txt_nguoi_dat_hang.TabIndex = 4;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(613, 19);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(60, 14);
            this.label2.TabIndex = 14;
            this.label2.Text = "Xử lý trong";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(339, 101);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(57, 14);
            this.label8.TabIndex = 14;
            this.label8.Text = "User xử lý";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(46, 100);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(102, 14);
            this.label7.TabIndex = 14;
            this.label7.Text = "User nhận đặt hàng";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(48, 130);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(99, 14);
            this.label5.TabIndex = 14;
            this.label5.Text = "Trạng thái đánh giá";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(317, 70);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(75, 14);
            this.label1.TabIndex = 14;
            this.label1.Text = "User đặt hàng";
            // 
            // f200_ds_dat_hang
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(968, 532);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.m_pnl_search_area);
            this.Controls.Add(this.m_lbl_header);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f200_ds_dat_hang";
            this.Text = "F200 - Danh sách các đặt hàng";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.f200_ds_dat_hang_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            this.m_pnl_out_place_dm.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.m_pnl_search_area.ResumeLayout(false);
            this.m_pnl_search_area.PerformLayout();
            this.ResumeLayout(false);

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
		#endregion

		#region Data Structure
		private enum e_col_Number{
			TEN_LOAI_DICH_VU = 7
            ,Y_KIEN_KHAC_TU_USER_DAT_HANG = 14
            ,THOI_GIAN_DAT_HANG = 3
            ,TEN_DON_VI = 4
            ,DIEN_THOAI = 6
            ,NGUOI_NHAN_DAT_HANG = 2
            ,USER_NV_DAT_HANG = 5
            ,TRANG_THAI_YC = 11
            ,DANH_GIA_TU_USER_DAT_HANG = 13
            ,NOI_DUNG_DAT_HANG = 8
            ,MA_DON_HANG = 1
            ,NGUOI_XU_LY = 10
            ,LOAI_THOI_GIAN_CAN_HOAN_THANH = 9
            ,THOI_GIAN_HOAN_THANH = 12
            , STT = 0
		}			
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_V_GD_DAT_HANG m_ds = new DS_V_GD_DAT_HANG();
		US_V_GD_DAT_HANG m_us = new US_V_GD_DAT_HANG();
		#endregion

		#region Private Methods
		private void format_controls(){
			CControlFormat.setFormStyle(this, new CAppContext_201(), IPFormStyle.DialogForm);
			CControlFormat.setC1FlexFormat(m_fg);
			CGridUtils.AddSearch_Handlers(m_fg);
            CGridUtils.AddSave_Excel_Handlers(m_fg);

            m_lbl_header.Font = new Font("Arial", 16);
            m_lbl_header.ForeColor = Color.DarkRed;
            m_lbl_header.TextAlign = ContentAlignment.MiddleCenter;

            m_dat_from_date.Value = DateTime.Now.AddDays(-7).AddHours(-1*DateTime.Now.Hour);
            m_dat_to_date.Value = DateTime.Now.AddHours(-1 * DateTime.Now.Hour).AddHours(23).AddMinutes(-1 * DateTime.Now.Minute).AddMinutes(59);
            m_dat_time_hoan_thanh_tu_ngay.Value = DateTime.Now.AddDays(-7).AddHours(-1 * DateTime.Now.Hour);
            m_dat_time_hoan_thanh_den_ngay.Value = DateTime.Now.AddHours(-1 * DateTime.Now.Hour).AddHours(23).AddMinutes(-1 * DateTime.Now.Minute).AddMinutes(59);

            this.ShowInTaskbar = true;
            this.MaximizeBox = true;
            this.MinimizeBox = true;

			set_define_events();
			this.KeyPreview = true;
		}
		private void set_initial_form_load(){						
			m_obj_trans = get_trans_object(m_fg);
            load_data_2_loai_thoi_gian_hoan_thanh();
            load_data_2_loai_trang_thai_don_hang();
            load_data_2_nguoi_xu_ly_don_hang();
            load_data_2_nguoi_nhan_dat_hang();
            load_data_2_danh_gia_tu_khach_hang();
            load_dât_2_loai_yeu_cau();
            m_txt_nguoi_dat_hang.AutoCompleteCustomSource = load_thong_tin_nguoi_dat_hang();
		}
        private void load_data_2_loai_thoi_gian_hoan_thanh()
        {
            US_CM_DM_TU_DIEN v_us_tu_dien = new US_CM_DM_TU_DIEN();
            DS_CM_DM_TU_DIEN v_ds_tu_dien = new DS_CM_DM_TU_DIEN();
            v_us_tu_dien.fill_tu_dien_cung_loai_ds(LOAI_TU_DIEN_TEXT.LOAI_TG_HOAN_THANH
                                                              , CM_DM_TU_DIEN.GHI_CHU
                                                              , v_ds_tu_dien);

            DataRow v_dr = v_ds_tu_dien.CM_DM_TU_DIEN.NewCM_DM_TU_DIENRow();
            v_dr[CM_DM_TU_DIEN.ID] = 0;
            v_dr[CM_DM_TU_DIEN.TEN] = "-- Tất cả --";
            v_ds_tu_dien.EnforceConstraints = false;
            v_ds_tu_dien.CM_DM_TU_DIEN.Rows.InsertAt(v_dr, 0);
            m_cbo_tho_han_xu_ly.DataSource = v_ds_tu_dien.CM_DM_TU_DIEN;
            m_cbo_tho_han_xu_ly.DisplayMember = CM_DM_TU_DIEN.TEN;
            m_cbo_tho_han_xu_ly.ValueMember = CM_DM_TU_DIEN.ID;
        }
        private void load_data_2_loai_trang_thai_don_hang()
        {
            US_CM_DM_TU_DIEN v_us_tu_dien = new US_CM_DM_TU_DIEN();
            DS_CM_DM_TU_DIEN v_ds_tu_dien = new DS_CM_DM_TU_DIEN();
            v_us_tu_dien.fill_tu_dien_cung_loai_ds(LOAI_TU_DIEN_TEXT.TRANG_THAI_DON_HANG
                                                              , CM_DM_TU_DIEN.GHI_CHU
                                                              , v_ds_tu_dien);

            DataRow v_dr = v_ds_tu_dien.CM_DM_TU_DIEN.NewCM_DM_TU_DIENRow();
            v_dr[CM_DM_TU_DIEN.ID] = 0;
            v_dr[CM_DM_TU_DIEN.TEN] = "-- Tất cả --";
            v_ds_tu_dien.EnforceConstraints = false;
            v_ds_tu_dien.CM_DM_TU_DIEN.Rows.InsertAt(v_dr, 0);

            m_cbo_trang_thai_don_hang.DataSource = v_ds_tu_dien.CM_DM_TU_DIEN;
            m_cbo_trang_thai_don_hang.DisplayMember = CM_DM_TU_DIEN.TEN;
            m_cbo_trang_thai_don_hang.ValueMember = CM_DM_TU_DIEN.ID;
        }
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(V_GD_DAT_HANG.TEN_LOAI_DICH_VU, e_col_Number.TEN_LOAI_DICH_VU);
			v_htb.Add(V_GD_DAT_HANG.Y_KIEN_KHAC_TU_USER_DAT_HANG, e_col_Number.Y_KIEN_KHAC_TU_USER_DAT_HANG);
			v_htb.Add(V_GD_DAT_HANG.THOI_GIAN_DAT_HANG, e_col_Number.THOI_GIAN_DAT_HANG);
			v_htb.Add(V_GD_DAT_HANG.TEN_DON_VI, e_col_Number.TEN_DON_VI);
			v_htb.Add(V_GD_DAT_HANG.DIEN_THOAI, e_col_Number.DIEN_THOAI);
			v_htb.Add(V_GD_DAT_HANG.NGUOI_NHAN_DAT_HANG, e_col_Number.NGUOI_NHAN_DAT_HANG);
			v_htb.Add(V_GD_DAT_HANG.USER_NV_DAT_HANG, e_col_Number.USER_NV_DAT_HANG);
			v_htb.Add(V_GD_DAT_HANG.TRANG_THAI_YC, e_col_Number.TRANG_THAI_YC);
			v_htb.Add(V_GD_DAT_HANG.DANH_GIA_TU_USER_DAT_HANG, e_col_Number.DANH_GIA_TU_USER_DAT_HANG);
			v_htb.Add(V_GD_DAT_HANG.NOI_DUNG_DAT_HANG, e_col_Number.NOI_DUNG_DAT_HANG);
			v_htb.Add(V_GD_DAT_HANG.MA_DON_HANG, e_col_Number.MA_DON_HANG);
			v_htb.Add(V_GD_DAT_HANG.NGUOI_XU_LY, e_col_Number.NGUOI_XU_LY);
			v_htb.Add(V_GD_DAT_HANG.LOAI_THOI_GIAN_CAN_HOAN_THANH, e_col_Number.LOAI_THOI_GIAN_CAN_HOAN_THANH);
			v_htb.Add(V_GD_DAT_HANG.THOI_GIAN_HOAN_THANH, e_col_Number.THOI_GIAN_HOAN_THANH);
									
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.V_GD_DAT_HANG.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(){
            DateTime v_dat_tu_ngay;
            if (m_dat_from_date.Checked) v_dat_tu_ngay = m_dat_from_date.Value;
            else v_dat_tu_ngay = CIPConvert.ToDatetime("01/01/1900");
            DateTime v_dat_den_ngay;
            if (m_dat_to_date.Checked) v_dat_den_ngay = m_dat_to_date.Value;
            else v_dat_den_ngay = CIPConvert.ToDatetime("01/01/1900");
            DateTime v_dat_hoan_thanh_tu_ngay;
            if (m_dat_time_hoan_thanh_tu_ngay.Checked) v_dat_hoan_thanh_tu_ngay = m_dat_time_hoan_thanh_tu_ngay.Value;
            else v_dat_hoan_thanh_tu_ngay = CIPConvert.ToDatetime("01/01/1900");
            DateTime v_dat_hoan_thanh_den_ngay;
            if (m_dat_time_hoan_thanh_den_ngay.Checked) v_dat_hoan_thanh_den_ngay = m_dat_time_hoan_thanh_den_ngay.Value;
            else v_dat_hoan_thanh_den_ngay = CIPConvert.ToDatetime("01/01/1900");
            string v_str_ma_don_hang = m_txt_ma_don_hang.Text.Trim();
            string v_str_user_nguoi_dat_hang = m_txt_nguoi_dat_hang.Text.Trim();
            decimal v_dc_id_thoi_gian_hen_hoan_thanh = CIPConvert.ToDecimal(m_cbo_tho_han_xu_ly.SelectedValue);
            decimal v_dc_id_trang_thai_don_hang = CIPConvert.ToDecimal(m_cbo_trang_thai_don_hang.SelectedValue);
            decimal v_dc_id_nguoi_xu_ly = CIPConvert.ToDecimal(m_cbo_nguoi_xu_ly.SelectedValue);
            decimal v_dc_id_nguoi_tiep_nhan = CIPConvert.ToDecimal(m_cbo_nguoi_nhan_dat_hang.SelectedValue);
            decimal v_dc_id_loai_yeu_cau = CIPConvert.ToDecimal(m_cbo_loai_yeu_cau.SelectedValue);
            decimal v_dc_id_danh_gia_tu_khach_hang = CIPConvert.ToDecimal(m_cbo_danh_gia_tu_khach_hang.SelectedValue);

            string v_str_da_danh_gia_yn = "N";
            if (m_rdb_danh_gia_all.Checked) v_str_da_danh_gia_yn = "A";
            if (m_rdb_danh_gia_yes.Checked) v_str_da_danh_gia_yn = "Y";
			m_ds = new DS_V_GD_DAT_HANG();
            m_ds.EnforceConstraints = false;
            m_us.load_ds_don_hang(v_dat_tu_ngay
                                , v_dat_den_ngay
                                , v_str_ma_don_hang
                                , v_str_user_nguoi_dat_hang
                                , v_dc_id_thoi_gian_hen_hoan_thanh
                                , v_dc_id_trang_thai_don_hang
                                , f002_main_form.m_dc_id_user
                                , v_str_da_danh_gia_yn
                                , v_dc_id_nguoi_tiep_nhan
                                , v_dc_id_nguoi_xu_ly
                                , v_dc_id_loai_yeu_cau
                                , v_dc_id_danh_gia_tu_khach_hang
                                , v_dat_hoan_thanh_tu_ngay
                                , v_dat_hoan_thanh_den_ngay
                                , m_ds);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
            CGridUtils.MakeSoTT((int)e_col_Number.STT, m_fg);
            m_lbl_so_luong_dat_hang.Text = "Số lượng đặt hàng: " + m_ds.V_GD_DAT_HANG.Rows.Count;
			m_fg.Redraw = true;
		}
        private AutoCompleteStringCollection load_thong_tin_nguoi_dat_hang()
        {
            US_DM_NGUOI_DAT_HANG v_us_dm_nguoi_dat_hang = new US_DM_NGUOI_DAT_HANG();
            DS_DM_NGUOI_DAT_HANG v_ds_dm_nguoi_dat_hang = new DS_DM_NGUOI_DAT_HANG();
            AutoCompleteStringCollection v_auto_complete_string_ten_nguoi_dat_hang = new AutoCompleteStringCollection();
            v_us_dm_nguoi_dat_hang.load_ds_nguoi_dat_hang(v_ds_dm_nguoi_dat_hang);
            if (v_ds_dm_nguoi_dat_hang.DM_NGUOI_DAT_HANG.Rows.Count > 0)
            {
                foreach (DataRow v_dr in v_ds_dm_nguoi_dat_hang.DM_NGUOI_DAT_HANG.Rows)
                {
                    v_auto_complete_string_ten_nguoi_dat_hang.Add(v_dr[DM_NGUOI_DAT_HANG.USER_TOPICA].ToString());
                }
            }
            return v_auto_complete_string_ten_nguoi_dat_hang;
        }
        private void load_data_2_nguoi_xu_ly_don_hang()
        {
            US_HT_NGUOI_SU_DUNG v_us_nguoi_dung = new US_HT_NGUOI_SU_DUNG();
            DS_HT_NGUOI_SU_DUNG v_ds_nguoi_dung = new DS_HT_NGUOI_SU_DUNG();
            v_us_nguoi_dung.LoadNguoiDungXuLy("", v_ds_nguoi_dung);

            DataRow v_dr = v_ds_nguoi_dung.HT_NGUOI_SU_DUNG.NewHT_NGUOI_SU_DUNGRow();
            v_dr[HT_NGUOI_SU_DUNG.ID] = 0;
            v_dr[HT_NGUOI_SU_DUNG.TEN_TRUY_CAP] = "- Tất cả -";
            v_ds_nguoi_dung.EnforceConstraints = false;
            v_ds_nguoi_dung.HT_NGUOI_SU_DUNG.Rows.InsertAt(v_dr, 0);

            m_cbo_nguoi_xu_ly.DataSource = v_ds_nguoi_dung.HT_NGUOI_SU_DUNG;
            m_cbo_nguoi_xu_ly.DisplayMember = HT_NGUOI_SU_DUNG.TEN_TRUY_CAP;
            m_cbo_nguoi_xu_ly.ValueMember = HT_NGUOI_SU_DUNG.ID;
        }
        private void load_data_2_nguoi_nhan_dat_hang()
        {
            US_HT_NGUOI_SU_DUNG v_us_nguoi_dung = new US_HT_NGUOI_SU_DUNG();
            DS_HT_NGUOI_SU_DUNG v_ds_nguoi_dung = new DS_HT_NGUOI_SU_DUNG();
            v_us_nguoi_dung.LoadNguoiDungTiepNhan("", v_ds_nguoi_dung);

            DataRow v_dr = v_ds_nguoi_dung.HT_NGUOI_SU_DUNG.NewHT_NGUOI_SU_DUNGRow();
            v_dr[HT_NGUOI_SU_DUNG.ID] = 0;
            v_dr[HT_NGUOI_SU_DUNG.TEN_TRUY_CAP] = "- Tất cả -";
            v_ds_nguoi_dung.EnforceConstraints = false;
            v_ds_nguoi_dung.HT_NGUOI_SU_DUNG.Rows.InsertAt(v_dr, 0);

            m_cbo_nguoi_nhan_dat_hang.DataSource = v_ds_nguoi_dung.HT_NGUOI_SU_DUNG;
            m_cbo_nguoi_nhan_dat_hang.DisplayMember = HT_NGUOI_SU_DUNG.TEN_TRUY_CAP;
            m_cbo_nguoi_nhan_dat_hang.ValueMember = HT_NGUOI_SU_DUNG.ID;
        }
        private void load_data_2_danh_gia_tu_khach_hang()
        {
            US_CM_DM_TU_DIEN v_us_tu_dien = new US_CM_DM_TU_DIEN();
            DS_CM_DM_TU_DIEN v_ds_tu_dien = new DS_CM_DM_TU_DIEN();
            v_us_tu_dien.fill_tu_dien_cung_loai_ds(LOAI_TU_DIEN_TEXT.HANG_DANH_GIA
                                                              , CM_DM_TU_DIEN.TEN
                                                              , v_ds_tu_dien);

            DataRow v_dr = v_ds_tu_dien.CM_DM_TU_DIEN.NewCM_DM_TU_DIENRow();
            v_dr[CM_DM_TU_DIEN.ID] = 0;
            v_dr[CM_DM_TU_DIEN.TEN] = "-- Tất cả --";
            v_ds_tu_dien.EnforceConstraints = false;
            v_ds_tu_dien.CM_DM_TU_DIEN.Rows.InsertAt(v_dr, 0);

            m_cbo_danh_gia_tu_khach_hang.DataSource = v_ds_tu_dien.CM_DM_TU_DIEN;
            m_cbo_danh_gia_tu_khach_hang.DisplayMember = CM_DM_TU_DIEN.TEN;
            m_cbo_danh_gia_tu_khach_hang.ValueMember = CM_DM_TU_DIEN.ID;
        }
        private void load_dât_2_loai_yeu_cau()
        {
            US_DM_LOAI_YEU_CAU v_us_loai_yeu_cau = new US_DM_LOAI_YEU_CAU();
            DS_DM_LOAI_YEU_CAU v_ds_loai_yeu_cau = new DS_DM_LOAI_YEU_CAU();
            v_us_loai_yeu_cau.load_ds_loai_dich_vu(v_ds_loai_yeu_cau);

            DataRow v_dr = v_ds_loai_yeu_cau.DM_LOAI_YEU_CAU.NewDM_LOAI_YEU_CAURow();
            v_dr[DM_LOAI_YEU_CAU.ID] = 0;
            v_dr[DM_LOAI_YEU_CAU.TEN_YEU_CAU] = "-- Tất cả --";
            v_ds_loai_yeu_cau.EnforceConstraints = false;
            v_ds_loai_yeu_cau.DM_LOAI_YEU_CAU.Rows.InsertAt(v_dr, 0);

            m_cbo_loai_yeu_cau.DataSource = v_ds_loai_yeu_cau.DM_LOAI_YEU_CAU;
            m_cbo_loai_yeu_cau.DisplayMember = DM_LOAI_YEU_CAU.TEN_YEU_CAU;
            m_cbo_loai_yeu_cau.ValueMember = DM_LOAI_YEU_CAU.ID;
        }
        private void grid2us_object(US_V_GD_DAT_HANG i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

		private void us_object2grid(US_V_GD_DAT_HANG i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}

		private void insert_v_gd_dat_hang(){
            f100_dat_hang_moi v_f100 = new f100_dat_hang_moi();
            v_f100.display_for_insert_form_master();
			load_data_2_grid();
		}

		private void update_v_gd_dat_hang(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
			grid2us_object(m_us, m_fg.Row);
            f100_dat_hang_moi v_f100 = new f100_dat_hang_moi();
            v_f100.display_for_update(m_us);
			load_data_2_grid();
		}
				
		private void delete_v_gd_dat_hang(){
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
			US_V_GD_DAT_HANG v_us = new US_V_GD_DAT_HANG();
			grid2us_object(v_us, m_fg.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_v_gd_dat_hang(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us, m_fg.Row);
		//	f200_ds_dat_hang_DE v_fDE = new f200_ds_dat_hang_DE();			
		//	v_fDE.display(m_us);
		}

        private void hoan_thanh_don_hang()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            grid2us_object(m_us, m_fg.Row);
            f100_dat_hang_moi v_f100 = new f100_dat_hang_moi();
            v_f100.display_for_update_hoan_thanh_don_hang(m_us);
            load_data_2_grid();
        }
        private void gui_danh_gia_khach_hang()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            grid2us_object(m_us, m_fg.Row);
            f103_danh_gia_don_hang v_f103 = new f103_danh_gia_don_hang();
            v_f103.display_to_danh_gia(m_us);
            load_data_2_grid();
        }
		#endregion

//
		//
		//		EVENT HANLDERS
		//
		//
        private void set_define_events()
        {
            m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
            m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
            m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
            m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
            m_cmd_tim_kiem.Click += new EventHandler(m_cmd_tim_kiem_Click);
            m_cmd_hoan_thanh.Click += new EventHandler(m_cmd_hoan_thanh_Click);
            m_txt_nguoi_dat_hang.KeyDown += new KeyEventHandler(m_txt_nguoi_dat_hang_KeyDown);
            m_cmd_danh_gia_cua_KH.Click += new EventHandler(m_cmd_danh_gia_cua_KH_Click);
        }

        void m_cmd_danh_gia_cua_KH_Click(object sender, EventArgs e)
        {
            try
            {
                gui_danh_gia_khach_hang();
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }
        }

        void m_txt_nguoi_dat_hang_KeyDown(object sender, KeyEventArgs e)
        {
            try
            {
                if (e.KeyCode == Keys.Enter)
                    load_data_2_grid();
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }   
        }
        void m_cmd_hoan_thanh_Click(object sender, EventArgs e)
        {
            try
            {
                hoan_thanh_don_hang();
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }
        }

        void m_cmd_tim_kiem_Click(object sender, EventArgs e)
        {
            try
            {
                load_data_2_grid();
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }
        }

        private void f200_ds_dat_hang_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		
		}

		private void m_cmd_exit_Click(object sender, EventArgs e) {
			try{
				this.Close();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_insert_Click(object sender, EventArgs e) {
			try{
				insert_v_gd_dat_hang();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_update_Click(object sender, EventArgs e) {
			try{
				update_v_gd_dat_hang();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_delete_Click(object sender, EventArgs e) {
			try{
				delete_v_gd_dat_hang();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

        
	}
}

