///************************************************
/// Generated by: LinhDH
/// Date: 13/03/2014 07:40:18
/// Goal: Create Form for V_DM_CAU_HOI_KO_TRA_LOI
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;

using IPCOREDS;
using IPCOREUS;
using IPCOREDS.CDBNames;
using TOSApp.App_Code;
using C1.Win.C1FlexGrid;
using IP.Core.IPSystemAdmin;

namespace TOSApp.DanhMuc
{
	public class f500_ds_nguoi_dai_dien : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
		private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
		internal SIS.Controls.Button.SiSButton m_cmd_delete;
		internal SIS.Controls.Button.SiSButton m_cmd_update;
		internal SIS.Controls.Button.SiSButton m_cmd_insert;
		internal SIS.Controls.Button.SiSButton m_cmd_exit;
		internal SIS.Controls.Button.SiSButton m_cmd_view;
        private Label m_lbl_header;
        private GroupBox m_grb_dm_cau_hoi;
        private GroupBox m_grb_ds_nguoi_dai_dien;
        private C1FlexGrid m_fg_nguoi_dai_dien;
        internal SIS.Controls.Button.SiSButton m_cmd_sua_nguoi_dai_dien;
        internal SIS.Controls.Button.SiSButton m_cmd_them_nguoi_dai_dien;
		private System.ComponentModel.IContainer components;

		public f500_ds_nguoi_dai_dien()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f500_ds_nguoi_dai_dien));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_them_nguoi_dai_dien = new SIS.Controls.Button.SiSButton();
            this.m_cmd_sua_nguoi_dai_dien = new SIS.Controls.Button.SiSButton();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_view = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.m_lbl_header = new System.Windows.Forms.Label();
            this.m_grb_dm_cau_hoi = new System.Windows.Forms.GroupBox();
            this.m_grb_ds_nguoi_dai_dien = new System.Windows.Forms.GroupBox();
            this.m_fg_nguoi_dai_dien = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.m_grb_dm_cau_hoi.SuspendLayout();
            this.m_grb_ds_nguoi_dai_dien.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg_nguoi_dai_dien)).BeginInit();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_them_nguoi_dai_dien);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_sua_nguoi_dai_dien);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_view);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 456);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(915, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_them_nguoi_dai_dien
            // 
            this.m_cmd_them_nguoi_dai_dien.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_them_nguoi_dai_dien.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_them_nguoi_dai_dien.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_them_nguoi_dai_dien.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_them_nguoi_dai_dien.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_them_nguoi_dai_dien.ImageIndex = 0;
            this.m_cmd_them_nguoi_dai_dien.ImageList = this.ImageList;
            this.m_cmd_them_nguoi_dai_dien.Location = new System.Drawing.Point(571, 4);
            this.m_cmd_them_nguoi_dai_dien.Name = "m_cmd_them_nguoi_dai_dien";
            this.m_cmd_them_nguoi_dai_dien.Size = new System.Drawing.Size(129, 28);
            this.m_cmd_them_nguoi_dai_dien.TabIndex = 2;
            this.m_cmd_them_nguoi_dai_dien.Text = "&Thêm người đại diện";
            // 
            // m_cmd_sua_nguoi_dai_dien
            // 
            this.m_cmd_sua_nguoi_dai_dien.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_sua_nguoi_dai_dien.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_sua_nguoi_dai_dien.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_sua_nguoi_dai_dien.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_sua_nguoi_dai_dien.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_sua_nguoi_dai_dien.ImageIndex = 10;
            this.m_cmd_sua_nguoi_dai_dien.ImageList = this.ImageList;
            this.m_cmd_sua_nguoi_dai_dien.Location = new System.Drawing.Point(700, 4);
            this.m_cmd_sua_nguoi_dai_dien.Name = "m_cmd_sua_nguoi_dai_dien";
            this.m_cmd_sua_nguoi_dai_dien.Size = new System.Drawing.Size(123, 28);
            this.m_cmd_sua_nguoi_dai_dien.TabIndex = 3;
            this.m_cmd_sua_nguoi_dai_dien.Text = "Sửa người đại diện";
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(268, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_insert.TabIndex = 0;
            this.m_cmd_insert.Text = "&Thêm";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(180, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_update.TabIndex = 1;
            this.m_cmd_update.Text = "&Sửa";
            // 
            // m_cmd_view
            // 
            this.m_cmd_view.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_view.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_view.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_view.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_view.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_view.ImageIndex = 18;
            this.m_cmd_view.ImageList = this.ImageList;
            this.m_cmd_view.Location = new System.Drawing.Point(92, 4);
            this.m_cmd_view.Name = "m_cmd_view";
            this.m_cmd_view.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_view.TabIndex = 21;
            this.m_cmd_view.Text = "Xem";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_delete.TabIndex = 14;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(823, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 4;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_fg.Location = new System.Drawing.Point(3, 16);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(382, 397);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            // 
            // m_lbl_header
            // 
            this.m_lbl_header.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_lbl_header.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_header.ForeColor = System.Drawing.Color.Maroon;
            this.m_lbl_header.Location = new System.Drawing.Point(0, 0);
            this.m_lbl_header.Name = "m_lbl_header";
            this.m_lbl_header.Size = new System.Drawing.Size(915, 40);
            this.m_lbl_header.TabIndex = 24;
            this.m_lbl_header.Text = "F500 - Danh sách người đại diện";
            this.m_lbl_header.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // m_grb_dm_cau_hoi
            // 
            this.m_grb_dm_cau_hoi.Controls.Add(this.m_fg);
            this.m_grb_dm_cau_hoi.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_grb_dm_cau_hoi.Location = new System.Drawing.Point(0, 40);
            this.m_grb_dm_cau_hoi.Name = "m_grb_dm_cau_hoi";
            this.m_grb_dm_cau_hoi.Size = new System.Drawing.Size(388, 416);
            this.m_grb_dm_cau_hoi.TabIndex = 26;
            this.m_grb_dm_cau_hoi.TabStop = false;
            this.m_grb_dm_cau_hoi.Text = "Danh sách đơn vị nội bộ";
            // 
            // m_grb_ds_nguoi_dai_dien
            // 
            this.m_grb_ds_nguoi_dai_dien.Controls.Add(this.m_fg_nguoi_dai_dien);
            this.m_grb_ds_nguoi_dai_dien.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_grb_ds_nguoi_dai_dien.Location = new System.Drawing.Point(388, 40);
            this.m_grb_ds_nguoi_dai_dien.Name = "m_grb_ds_nguoi_dai_dien";
            this.m_grb_ds_nguoi_dai_dien.Size = new System.Drawing.Size(527, 416);
            this.m_grb_ds_nguoi_dai_dien.TabIndex = 27;
            this.m_grb_ds_nguoi_dai_dien.TabStop = false;
            this.m_grb_ds_nguoi_dai_dien.Text = "Danh sách người đại diện của đơn vị";
            // 
            // m_fg_nguoi_dai_dien
            // 
            this.m_fg_nguoi_dai_dien.ColumnInfo = resources.GetString("m_fg_nguoi_dai_dien.ColumnInfo");
            this.m_fg_nguoi_dai_dien.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_fg_nguoi_dai_dien.Location = new System.Drawing.Point(3, 16);
            this.m_fg_nguoi_dai_dien.Name = "m_fg_nguoi_dai_dien";
            this.m_fg_nguoi_dai_dien.Size = new System.Drawing.Size(521, 397);
            this.m_fg_nguoi_dai_dien.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg_nguoi_dai_dien.Styles"));
            this.m_fg_nguoi_dai_dien.TabIndex = 21;
            // 
            // f500_ds_nguoi_dai_dien
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(915, 492);
            this.Controls.Add(this.m_grb_ds_nguoi_dai_dien);
            this.Controls.Add(this.m_grb_dm_cau_hoi);
            this.Controls.Add(this.m_lbl_header);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f500_ds_nguoi_dai_dien";
            this.Text = "F500 - Danh sách người đại diện";
            this.Load += new System.EventHandler(this.f500_ds_nguoi_dai_dien_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.m_grb_dm_cau_hoi.ResumeLayout(false);
            this.m_grb_ds_nguoi_dai_dien.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg_nguoi_dai_dien)).EndInit();
            this.ResumeLayout(false);

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
        public void display_view_qlht()
        {
            m_e_form_mode = e_formMode.VIEW_QLHT;
            this.ShowDialog();
        }
		#endregion

		#region Data Structure
		private enum e_col_Number{
			TEN_DON_VI = 2            ,MA_DON_VI = 1
		}
        private enum e_col_Number_Nguoi_dai_dien
        {
            CHUC_VU = 4
                ,
            TEN_NGUOI_DAI_DIEN = 1
                ,
            DIEN_THOAI = 2
                , EMAIL = 3

        }
        private enum e_formMode
        {
            VIEW_TOAN_BO = 0
            , VIEW_QLHT = 1
        }
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;
        DS_CM_DM_TU_DIEN m_ds = new DS_CM_DM_TU_DIEN();
        US_CM_DM_TU_DIEN m_us = new US_CM_DM_TU_DIEN();
        
        ITransferDataRow m_obj_trans_nguoi_dai_dien;
        DS_V_DM_NGUOI_DAI_DIEN m_ds_nguoi_dai_dien = new DS_V_DM_NGUOI_DAI_DIEN();
        US_V_DM_NGUOI_DAI_DIEN m_us_nguoi_dai_dien = new US_V_DM_NGUOI_DAI_DIEN();

        e_formMode m_e_form_mode = e_formMode.VIEW_TOAN_BO;
        #endregion

		#region Private Methods
		private void format_controls(){
            CControlFormat.setFormStyle(this, new CAppContext_201(), IPFormStyle.DialogForm);
            CControlFormat.setC1FlexFormat(m_fg);
            CGridUtils.AddSearch_Handlers(m_fg);
            CGridUtils.AddSave_Excel_Handlers(m_fg);

            m_lbl_header.Font = new Font("Arial", 16);
            m_lbl_header.ForeColor = Color.DarkRed;
            m_lbl_header.TextAlign = ContentAlignment.MiddleCenter;

            this.MaximizeBox = true;
            this.MinimizeBox = true;

            m_cmd_view.Visible = false;
            m_cmd_delete.Visible = false;
            m_cmd_insert.Focus();
			set_define_events();
			this.KeyPreview = true;		
		}
		private void set_initial_form_load(){
			m_obj_trans = get_trans_object(m_fg);
            m_obj_trans_nguoi_dai_dien = get_trans_object_cau_tra_loi(m_fg_nguoi_dai_dien);

            load_data_2_grid();
            grid2us_object(m_us, 1);
            load_data_2_grid_nguoi_dai_dien(m_us.dcID);

            switch (m_e_form_mode)
            {
                case e_formMode.VIEW_TOAN_BO:
                    break;
                case e_formMode.VIEW_QLHT:
                    m_grb_dm_cau_hoi.Text = "Danh sách trường";
                    m_grb_ds_nguoi_dai_dien.Text = "Danh sách QLHT của trường";
                    m_lbl_header.Text = "F503 - Tra cứu danh sách QLHT";
                    this.Text = "F503 - Tra cứu danh sách QLHT";
                    break;
            }
		}	
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(CM_DM_TU_DIEN.TEN, e_col_Number.TEN_DON_VI);
            v_htb.Add(CM_DM_TU_DIEN.MA_TU_DIEN, e_col_Number.MA_DON_VI);									
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.CM_DM_TU_DIEN.NewRow());
			return v_obj_trans;			
		}
        private ITransferDataRow get_trans_object_cau_tra_loi(C1.Win.C1FlexGrid.C1FlexGrid i_fg)
        {
            Hashtable v_htb = new Hashtable();
            v_htb.Add(V_DM_NGUOI_DAI_DIEN.NDD_CHUC_VU, e_col_Number_Nguoi_dai_dien.CHUC_VU);
            v_htb.Add(V_DM_NGUOI_DAI_DIEN.NDD_HO_TEN, e_col_Number_Nguoi_dai_dien.TEN_NGUOI_DAI_DIEN);
            v_htb.Add(V_DM_NGUOI_DAI_DIEN.NDD_DIEN_THOAI, e_col_Number_Nguoi_dai_dien.DIEN_THOAI);
            v_htb.Add(V_DM_NGUOI_DAI_DIEN.NDD_EMAIL, e_col_Number_Nguoi_dai_dien.EMAIL);

            ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg, v_htb, m_ds_nguoi_dai_dien.V_DM_NGUOI_DAI_DIEN.NewRow());
            return v_obj_trans;
        }
        
        private void load_data_2_grid(){						
			m_ds = new DS_CM_DM_TU_DIEN();
            switch (m_e_form_mode)
            {
                case e_formMode.VIEW_TOAN_BO:
                    m_us.fill_tu_dien_cung_loai_ds(LOAI_TU_DIEN_TEXT.PHONG_BAN_NOI_BO, CM_DM_TU_DIEN.ID, m_ds);
                    break;
                case e_formMode.VIEW_QLHT:
                    m_us.fill_tu_dien_by_procedure("pr_CM_DM_TU_DIEN_Load_Phong_QLHT", "", m_ds);
                    break;
            }
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
            m_fg.Redraw = true;
            load_data_2_grid_nguoi_dai_dien(0);
		}
        private void load_data_2_grid_nguoi_dai_dien(decimal ip_dc_id_don_vi)
        {
            m_us_nguoi_dai_dien.dcID_DON_VI = ip_dc_id_don_vi;
            switch (m_e_form_mode)
            {
                case e_formMode.VIEW_TOAN_BO:
                    m_us_nguoi_dai_dien.strNDD_CHUC_VU = "";
                    break;
                case e_formMode.VIEW_QLHT:
                    m_us_nguoi_dai_dien.strNDD_CHUC_VU = "QLHT";
                    break;
            }
            m_ds_nguoi_dai_dien = new DS_V_DM_NGUOI_DAI_DIEN();
            m_us_nguoi_dai_dien.load_ds_nguoi_dai_dien_by_id_to_chuc(m_ds_nguoi_dai_dien); 
            m_fg_nguoi_dai_dien.Redraw = false;
            CGridUtils.Dataset2C1Grid(m_ds_nguoi_dai_dien, m_fg_nguoi_dai_dien, m_obj_trans_nguoi_dai_dien);
            m_fg_nguoi_dai_dien.Redraw = true;
        }
        private void load_ds_nguoi_dai_dien(int ip_i_cau_hoi_row)
        {
            if (!HelpUtils.is_validated_edit_grid_row(ip_i_cau_hoi_row, m_fg)) return;
            US_CM_DM_TU_DIEN v_us_dm = new US_CM_DM_TU_DIEN();
            grid2us_object(v_us_dm, m_fg.Row);
            load_data_2_grid_nguoi_dai_dien(v_us_dm.dcID);
        }
        
        private void grid2us_object(US_CM_DM_TU_DIEN i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

        private void grid2us_object_nguoi_dai_dien(US_V_DM_NGUOI_DAI_DIEN i_us
            , int i_grid_row)
        {
            DataRow v_dr;
            v_dr = (DataRow)m_fg_nguoi_dai_dien.Rows[i_grid_row].UserData;
            m_obj_trans_nguoi_dai_dien.GridRow2DataRow(i_grid_row, v_dr);
            i_us.DataRow2Me(v_dr);
        }

		private void us_object2grid(US_V_DM_CAU_HOI_KO_TRA_LOI i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}

        private void insert_nguoi_dai_dien()
        {
            f501_dm_nguoi_dai_dien v_f501 = new f501_dm_nguoi_dai_dien();
            grid2us_object(m_us, m_fg.Row);
            v_f501.display_for_insert_ndd(m_us.dcID);
            load_data_2_grid_nguoi_dai_dien(m_us.dcID);
		}

        private void update_nguoi_dai_dien()
        {
            if (!HelpUtils.is_validated_edit_grid_row(m_fg_nguoi_dai_dien.Row, m_fg_nguoi_dai_dien)) return;
            grid2us_object_nguoi_dai_dien(m_us_nguoi_dai_dien, m_fg_nguoi_dai_dien.Row);
            f501_dm_nguoi_dai_dien v_f501 = new f501_dm_nguoi_dai_dien();
            v_f501.display_for_update_ndd(m_us_nguoi_dai_dien);
			load_data_2_grid_nguoi_dai_dien(m_us_nguoi_dai_dien.dcID_DON_VI);
		}
				
		private void delete_nguoi_dai_dien(){
            if (!HelpUtils.is_validated_edit_grid_row(m_fg_nguoi_dai_dien.Row, m_fg)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
            US_V_DM_NGUOI_DAI_DIEN v_us = new US_V_DM_NGUOI_DAI_DIEN();
            grid2us_object_nguoi_dai_dien(v_us, m_fg_nguoi_dai_dien.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_v_dm_cau_hoi_ko_tra_loi(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us, m_fg.Row);
		//	f500_ds_nguoi_dai_dien_DE v_fDE = new f500_ds_nguoi_dai_dien_DE();			
		//	v_fDE.display(m_us);
		}
		private void set_define_events(){
			m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
			m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
			m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
			m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
			m_cmd_view.Click += new EventHandler(m_cmd_view_Click);
            this.KeyDown += new KeyEventHandler(f500_ds_nguoi_dai_dien_KeyDown);
            m_cmd_them_nguoi_dai_dien.Click += new EventHandler(m_cmd_them_nguoi_dai_dien_Click);
            m_cmd_sua_nguoi_dai_dien.Click += new EventHandler(m_cmd_sua_nguoi_dai_dien_Click);

            m_fg.Click += new EventHandler(m_fg_Click);
		}

        void f500_ds_nguoi_dai_dien_KeyDown(object sender, KeyEventArgs e)
        {
            try
            {
                switch (e.KeyCode)
                {
                    case Keys.Escape:
                        this.Close();
                        break;
                }
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }
        }
      

//
		//
		//		EVENT HANLDERS
		//
		//
		private void f500_ds_nguoi_dai_dien_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		
		}

		private void m_cmd_exit_Click(object sender, EventArgs e) {
			try{
				this.Close();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_insert_Click(object sender, EventArgs e) {
			try{
                m_us.dcID_LOAI_TU_DIEN = LOAI_TU_DIEN_ID.PHONG_BAN_NOI_BO;
                f102_TuDien_DE v_f102_detail = new f102_TuDien_DE();
                v_f102_detail.InsertObj(m_us);
                load_data_2_grid();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_update_Click(object sender, EventArgs e) {
			try{
                grid2us_object(m_us, m_fg.Row);
                f102_TuDien_DE v_f102_detail = new f102_TuDien_DE();
                v_f102_detail.UpdateObj(m_us);
                load_data_2_grid();
                load_data_2_grid_nguoi_dai_dien(m_us.dcID);
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_delete_Click(object sender, EventArgs e) {
			try{
				delete_nguoi_dai_dien();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_view_Click(object sender, EventArgs e) {
			try{
				view_v_dm_cau_hoi_ko_tra_loi();
			}
			catch (Exception v_e){
				CSystemLog_100.ExceptionHandle(v_e);
			}
		}

        void m_fg_Click(object sender, EventArgs e)
        {
            try
            {
                load_ds_nguoi_dai_dien(m_fg.Row);
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }
        }

        void m_cmd_sua_nguoi_dai_dien_Click(object sender, EventArgs e)
        {
            try
            {
                update_nguoi_dai_dien();
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }
        }

        void m_cmd_them_nguoi_dai_dien_Click(object sender, EventArgs e)
        {
            try
            {
                insert_nguoi_dai_dien();
            }
            catch (Exception v_e)
            {
                CSystemLog_100.ExceptionHandle(v_e);
            }
        }
        #endregion

	}
}

